const D119_QUESTIONS = [
  // UNITS 2-4: Developmental Milestones
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"At what age should an infant demonstrate a social smile?",choices:["1-2 weeks","4-6 weeks","3-4 months","6 months"],answer:1,explain:"Social smile appears at 4-6 weeks. If absent by 2 months = developmental red flag requiring evaluation."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"The Denver Developmental Screening Test (ASQ-3) screens which domains?",choices:["Motor only","Language and social only","Personal-social, fine motor, language, gross motor","Cognitive and academic only"],answer:2,explain:"ASQ-3 (Ages and Stages Questionnaire): screens communication, gross motor, fine motor, problem-solving, and personal-social domains."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"A 24-month-old cannot say 2-word phrases and has fewer than 50 words. What is the appropriate next step?",choices:["Reassure parents — boys develop more slowly","Refer for speech-language evaluation and hearing test","Recheck at 3-year visit","Screen for autism with M-CHAT only"],answer:1,explain:"Language red flag: no 2-word phrases by 24 months. Refer for speech eval AND hearing test (hearing loss is common cause of language delay)."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"APGAR scoring is done at what time points after birth?",choices:["1 and 3 minutes","1 and 5 minutes","2 and 5 minutes","1, 5, and 10 minutes"],answer:1,explain:"APGAR scored at 1 and 5 minutes. If 5-min score <7, repeat at 10 min. Scores: 7-10 normal, 4-6 moderate concern, 0-3 requires immediate resuscitation."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"APGAR score components (APGAR mnemonic)?",choices:["Activity, Pulse, Grimace, Appearance, Respiration","Alertness, Posture, Growth, Activity, Reflexes","Appearance (color), Pulse, Grimace, Activity, Respiration","Apnea, Pulse, Glucose, Appearance, Respiration"],answer:2,explain:"APGAR: Appearance (color), Pulse, Grimace (reflex irritability), Activity (muscle tone), Respiration. Each scored 0-2, max 10."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"Tanner Stage 2 in girls is characterized by what first change?",choices:["Pubic hair","Menarche","Breast budding (thelarche)","Axillary hair"],answer:2,explain:"Tanner Stage 2 girls: breast budding is first sign of puberty (thelarche), typically ages 8-13. Pubic hair may appear slightly after. Average menarche at Tanner 3-4."},
  {unit:"U2-4",topic:"Development - Milestones",type:"mc",q:"The Barlow and Ortolani maneuvers are used to screen for which condition?",choices:["Tibial torsion","Developmental dysplasia of the hip (DDH)","Legg-Calve-Perthes disease","Scoliosis"],answer:1,explain:"Barlow (posterior hip dislocation) and Ortolani (reduction of dislocated hip) maneuvers screen for DDH in newborns. Positive = clunk sensation."},
  {unit:"U2-4",topic:"Development - ADHD",type:"mc",q:"DSM-5 ADHD diagnosis requires symptoms present before what age and in how many settings?",choices:["Age 7 in 1 setting","Age 12 in 2 or more settings","Age 10 in 2 or more settings","Age 7 in any setting"],answer:1,explain:"DSM-5 ADHD: 6+ inattentive OR 6+ hyperactive symptoms (5+ if age ≥17), present BEFORE age 12, in 2+ settings, causing impairment."},

  // Newborn Assessment
  {unit:"U2-4",topic:"Newborn",type:"mc",q:"What is the normal newborn respiratory rate?",choices:["10-20/min","20-30/min","30-60/min","60-80/min"],answer:2,explain:"Normal newborn RR: 30-60 breaths/min. HR: 120-160/min. RR >60 = tachypnea, evaluate for respiratory distress."},
  {unit:"U2-4",topic:"Newborn",type:"mc",q:"A newborn has central cyanosis at 10 minutes of life. What is the appropriate action?",choices:["Normal — acrocyanosis is expected","Supplemental oxygen and evaluate for congenital heart disease","Observe for 30 minutes then reassess","Apply warming blankets only"],answer:1,explain:"Acrocyanosis (blue hands/feet) is NORMAL in newborns. Central cyanosis (blue lips/tongue) is ABNORMAL at any time and requires immediate evaluation (CHD, respiratory distress)."},

  // Well Child Visits
  {unit:"U2-4",topic:"Well Child",type:"mc",q:"At what ages are routine well child visits recommended in the first year? (AAP schedule)",choices:["1, 2, 4, 6, 9, 12 months","2, 4, 6, 9, 12 months","1, 2, 4, 6, 12 months","Birth, 1, 3, 6, 9, 12 months"],answer:0,explain:"AAP Bright Futures schedule: newborn (3-5 days), then 1, 2, 4, 6, 9, 12 months in first year. Then 15, 18, 24, 30 months, then annually."},
  {unit:"U2-4",topic:"Well Child",type:"mc",q:"The HEEADSSS assessment is used for which age group?",choices:["Newborns","Toddlers 2-5 years","Adolescents","School-age children 6-11"],answer:2,explain:"HEEADSSS: adolescent psychosocial assessment — Home, Education/Employment, Eating, Activities, Drugs, Sexuality, Suicide/depression, Safety. Used ages 11-21."},

  // Immunizations
  {unit:"U2-4",topic:"Immunizations",type:"mc",q:"At the 2-month well child visit, which vaccines are given?",choices:["DTaP, Hib, PCV, IPV, HepB, Rotavirus","MMR, Varicella, HepA, HepB","DTaP, Hib, PCV, IPV only","MMR, DTaP, IPV, Varicella"],answer:0,explain:"2-month vaccines: DTaP, Hib, PCV13, IPV, HepB (2nd dose), Rotavirus. The 'big 6' at 2, 4, and 6 months."},
  {unit:"U2-4",topic:"Immunizations",type:"mc",q:"MMR and Varicella vaccines are first given at what age?",choices:["6 months","9 months","12-15 months","18 months"],answer:2,explain:"MMR and Varicella: first dose at 12-15 months, second dose at 4-6 years. Cannot give before 12 months due to maternal antibodies."},

  // Infectious Disease
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"Most common cause of childhood infectious illness?",choices:["Bacteria","Fungi","Viruses","Parasites"],answer:2,explain:"Viruses are the most common cause of childhood infections (URI, otitis media, gastroenteritis, etc.). Most URIs are viral and do NOT require antibiotics."},
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"A child with fever, confluent maculopapular rash starting on face spreading downward, cough, coryza, and conjunctivitis. Koplik spots seen on buccal mucosa. Diagnosis?",choices:["Rubella","Roseola","Rubeola (measles)","Erythema infectiosum"],answer:2,explain:"Measles (Rubeola): 3 C's (cough, coryza, conjunctivitis) + fever + maculopapular rash head-to-toe + Koplik spots (pathognomonic). Reportable disease."},
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"A child with fever for 3-4 days, then fever breaks and a rose-colored rash appears on trunk spreading outward. Diagnosis?",choices:["Measles","Rubella","Roseola (HHV-6)","Fifth disease"],answer:2,explain:"Roseola (Exanthem Subitum): HHV-6/7, high fever 3-5 days, fever breaks, rash appears. Classic 'fever first, rash after fever breaks.' Ages 6 months - 2 years."},
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"'Slapped cheek' rash followed by lacy reticular rash on extremities in a child. School-age, low-grade fever. Diagnosis?",choices:["Roseola","Rubella","Erythema infectiosum (Fifth disease, Parvovirus B19)","Scarlet fever"],answer:2,explain:"Fifth disease: Parvovirus B19, slapped cheek appearance, followed by lacy reticular rash on arms/legs. Most contagious BEFORE rash — no longer contagious once rash appears. Dangerous in sickle cell and pregnancy."},
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"A child with sore throat, fever, and a sandpaper-textured rash on trunk sparing the face, with strawberry tongue and circumoral pallor. Culture grows Group A Strep. Diagnosis?",choices:["Kawasaki disease","Scarlet fever","Roseola","Meningococcemia"],answer:1,explain:"Scarlet fever: Group A Strep pharyngitis + diffuse sandpaper rash, circumoral pallor, strawberry tongue. Treat with penicillin/amoxicillin x 10 days to prevent rheumatic fever."},
  {unit:"U5",topic:"Infectious Disease",type:"mc",q:"Lyme disease first-line treatment in children (except <8 years for doxycycline)?",choices:["Azithromycin 5 days","Doxycycline 100mg BID x 14-21 days (age ≥8)","Amoxicillin 50mg/kg/day x 14-21 days (age <8)","Ceftriaxone IV for all cases"],answer:2,explain:"Lyme disease: age ≥8 = doxycycline x 14-21 days. Age <8 = amoxicillin (avoid doxycycline — dental staining). IV ceftriaxone for disseminated (cardiac, neuro) disease."},

  // Respiratory
  {unit:"U7",topic:"Respiratory - Peds",type:"mc",q:"A 2yo with barky cough, inspiratory stridor, low-grade fever, and hoarse voice. Worsens at night. Diagnosis and treatment?",choices:["Epiglottitis — immediate intubation","Croup (laryngotracheobronchitis) — dexamethasone ± nebulized racemic epinephrine","Foreign body aspiration — bronchoscopy","Bacterial tracheitis — IV antibiotics"],answer:1,explain:"Croup: barky 'seal-like' cough, stridor, worse at night, para-influenza virus. Mild-moderate: dexamethasone 0.6mg/kg. Severe: add nebulized racemic epinephrine. Steeple sign on X-ray."},
  {unit:"U7",topic:"Respiratory - Peds",type:"mc",q:"A toddler suddenly develops unilateral wheezing, respiratory distress, and coughing while playing with toys. No fever. What is the priority concern?",choices:["RSV bronchiolitis","Croup","Foreign body aspiration","Asthma exacerbation"],answer:2,explain:"Sudden unilateral wheezing + no fever in toddler = foreign body aspiration until proven otherwise. Obtain CXR (may show unilateral hyperinflation or air trapping). Requires bronchoscopy."},
  {unit:"U7",topic:"Respiratory - Peds",type:"mc",q:"RSV bronchiolitis — what is the mainstay of treatment?",choices:["Albuterol nebulization","Systemic steroids","Supportive care — hydration and oxygenation","Ribavirin antiviral"],answer:2,explain:"Bronchiolitis (RSV): supportive care is standard — suction, hydration, O2 if needed. Bronchodilators, steroids, and antibiotics are NOT recommended routinely."},

  // Cardiac - Peds
  {unit:"U8",topic:"Cardiac - Peds",type:"mc",q:"Which innocent murmur is described as a vibratory, musical, low-pitched systolic ejection murmur at the LLSB in children 3-8 years?",choices:["Pulmonary ejection murmur","Venous hum","Still's murmur","Supraclavicular bruit"],answer:2,explain:"Still's murmur (most common innocent murmur): vibratory/musical, grade 1-3, systolic ejection at LLSB, loudest supine, decreases/disappears with standing/Valsalva."},
  {unit:"U8",topic:"Cardiac - Peds",type:"mc",q:"An infant with Down syndrome has a harsh pansystolic murmur at LLSB with loud S2 and frequent respiratory infections. Most likely diagnosis?",choices:["ASD","VSD","AV canal defect (AVSD)","Patent ductus arteriosus"],answer:2,explain:"AV canal defect (endocardial cushion defect): strongly associated with Down syndrome (trisomy 21). Involves ASD + VSD + abnormal AV valves. Requires surgical repair."},
  {unit:"U8",topic:"Cardiac - Peds",type:"mc",q:"A cyanotic neonate with a 'boot-shaped heart' on CXR and harsh systolic murmur. Most likely diagnosis?",choices:["Transposition of great arteries","Tetralogy of Fallot","Total anomalous pulmonary venous return","Tricuspid atresia"],answer:1,explain:"Tetralogy of Fallot: VSD + pulmonary stenosis + overriding aorta + RVH. Boot-shaped heart on CXR. Most common cyanotic CHD after first year. Tet spells — knee-chest position."},

  // GI - Peds
  {unit:"U9",topic:"GI - Peds",type:"mc",q:"A 3-week-old male with projectile non-bilious vomiting after every feeding, hungry immediately after vomiting, and an olive-shaped mass in epigastrium. Diagnosis?",choices:["GERD","Intussusception","Pyloric stenosis","Hirschsprung disease"],answer:2,explain:"Pyloric stenosis: non-bilious projectile vomiting at 2-6 weeks (male > female), olive mass, hypochloremic hypokalemic metabolic alkalosis. Ultrasound confirms. Pyloromyotomy is treatment."},
  {unit:"U9",topic:"GI - Peds",type:"mc",q:"A 9-month-old with sudden colicky abdominal pain, drawing up knees, 'currant jelly' stools, and sausage-shaped abdominal mass. Diagnosis?",choices:["Pyloric stenosis","Appendicitis","Intussusception","Meckel's diverticulum"],answer:2,explain:"Intussusception: telescoping of bowel, peak 6-18 months. Currant jelly stools (bloody mucus), episodic colicky pain, palpable mass. Air enema is diagnostic and therapeutic."},
  {unit:"U9",topic:"GI - Peds",type:"mc",q:"A newborn passes no meconium in first 24-48 hours of life. Rectal exam causes explosive release of stool. Most likely diagnosis?",choices:["Pyloric stenosis","Hirschsprung disease","Meconium ileus","Intussusception"],answer:1,explain:"Hirschsprung disease: absence of ganglion cells in colon. Delayed meconium passage >48 hours, explosive decompression on rectal exam, risk of toxic megacolon. Suction rectal biopsy confirms."},

  // MSK - Peds
  {unit:"U11",topic:"MSK - Peds",type:"mc",q:"A 6yo limping with insidious onset hip pain, antalgic gait, decreased internal rotation. X-ray shows flattened femoral head. Diagnosis?",choices:["Developmental dysplasia of hip","Slipped capital femoral epiphysis","Legg-Calve-Perthes disease","Septic arthritis"],answer:2,explain:"Legg-Calve-Perthes: avascular necrosis of femoral head, ages 4-10, boys > girls. Flattened femoral head on X-ray. Treat with containment therapy."},
  {unit:"U11",topic:"MSK - Peds",type:"mc",q:"An obese 13yo male with limp and hip/knee pain. X-ray shows displacement of femoral epiphysis. Diagnosis?",choices:["Legg-Calve-Perthes","Septic arthritis","Slipped capital femoral epiphysis (SCFE)","DDH"],answer:2,explain:"SCFE: obese adolescent male, hip/groin pain radiating to knee, X-ray shows 'ice cream falling off cone.' Bilateral in 20-40%. Urgent surgical pinning required — non-weightbearing."},
  {unit:"U11",topic:"MSK - Peds",type:"mc",q:"A 12yo boy with knee pain at the tibial tuberosity during sports, tender swelling at tuberosity. No joint effusion. Diagnosis?",choices:["Septic arthritis","Patellofemoral pain syndrome","Osgood-Schlatter disease","Meniscus tear"],answer:2,explain:"Osgood-Schlatter: traction apophysitis at tibial tuberosity, active adolescents during growth spurt, worse with activity, tender tibial tuberosity. Treat with activity modification, stretching, ice."},

  // Neuro - Peds
  {unit:"U12",topic:"Neurology - Peds",type:"mc",q:"A 2yo has a generalized tonic-clonic seizure lasting 2 minutes with temperature of 103.5F. No neurologic deficits. Prior episodes. What is this most likely?",choices:["Epilepsy requiring AED therapy","Complex febrile seizure","Simple febrile seizure","Meningitis — immediate LP"],answer:2,explain:"Simple febrile seizure: age 6mo-6yr, generalized, <15 min, occurs once in 24hrs with fever. No treatment needed. Complex = >15 min, focal, or recurs within 24 hrs."},
  {unit:"U12",topic:"Neurology - Peds",type:"mc",q:"Autism Spectrum Disorder (ASD) — which screening tool is used at the 18-month and 24-month well child visits?",choices:["ASQ-3","NICHQ Vanderbilt","M-CHAT-R/F","SCARED"],answer:2,explain:"M-CHAT-R/F (Modified Checklist for Autism in Toddlers): ASD screening at 16-30 months. AAP recommends at 18 and 24-month well child visits."},

  // Endocrine - Peds
  {unit:"U10",topic:"Endocrine - Peds",type:"mc",q:"A 7yo girl begins developing breast buds. What is the appropriate evaluation?",choices:["Normal — can begin puberty at age 7","Bone age X-ray and refer to pediatric endocrinology if early","Reassure — early thelarche is always benign","Start GnRH agonist immediately"],answer:1,explain:"Precocious puberty in girls: breast development before age 8 (or pubic hair before 8). Evaluate with bone age, LH, FSH, estradiol. Refer to endocrinology. GnRH agonist used if central PP confirmed."},
  {unit:"U10",topic:"Endocrine - Peds",type:"mc",q:"Which condition is most associated with childhood onset Type 1 DM?",choices:["Insulin resistance","Autoimmune destruction of beta cells","Obesity","Mitochondrial dysfunction"],answer:1,explain:"Type 1 DM: autoimmune destruction of pancreatic beta cells (islets of Langerhans). Anti-GAD, anti-islet cell antibodies. Requires insulin therapy. DKA is common presentation."},

  // Hematology - Peds
  {unit:"U13",topic:"Hematology - Peds",type:"mc",q:"A 10-month-old exclusively breastfed infant has pallor, fatigue, and irritability. CBC shows microcytic hypochromic anemia. Most likely diagnosis?",choices:["B12 deficiency","Thalassemia","Iron deficiency anemia","Sickle cell disease"],answer:2,explain:"Iron deficiency anemia: most common anemia in children ages 6mo-3yr. Breast milk is low in iron — start iron supplementation at 4 months for breastfed infants. Microcytic, hypochromic."},
  {unit:"U13",topic:"Hematology - Peds",type:"mc",q:"A child with sickle cell disease presents with sudden severe bone pain in extremities, chest pain, and fever. Priority assessment?",choices:["Acute chest syndrome vs vaso-occlusive crisis","Septic arthritis","Pulmonary embolism","Osteomyelitis only"],answer:0,explain:"Sickle cell crises: vaso-occlusive (most common — bone pain), acute chest syndrome (chest pain + fever + infiltrate = life-threatening), stroke, splenic sequestration. Fever = sepsis risk — empiric antibiotics."},

  // Case Scenarios
  {unit:"U5",topic:"Infectious Disease - Case",type:"case",q:"A 4yo unvaccinated child presents with high fever, drooling, severe sore throat, and 'tripod positioning.' Refuses to lie down. HR 140, RR 30. On exam, the child appears toxic and you can barely see the throat. What should you do?",choices:["Attempt to visualize throat with tongue depressor","Do nothing to agitate child — maintain airway, call ENT/anesthesia/EMS immediately","Give oral amoxicillin and admit to floor","Perform lateral neck X-ray first"],answer:1,explain:"Epiglottitis emergency: do NOT agitate child or attempt throat exam. Maintain calm environment, keep child in position of comfort, call ENT and anesthesia stat for airway management. H. influenzae type b (rare with vaccination)."},
  {unit:"U12",topic:"Neuro - Case",type:"case",q:"A mother brings her 18-month-old because 'he doesn't talk much, doesn't wave bye-bye, and stopped saying mama.' He doesn't make eye contact. What is the priority action?",choices:["Reassure — boys talk later","Refer for speech therapy only","Immediate referral for autism evaluation (M-CHAT positive) + audiology","Wait until 2-year visit to reassess"],answer:2,explain:"Regression of language + lack of eye contact + no pointing/waving = ASD red flags. Loss of previously acquired skills = IMMEDIATE referral (not watchful waiting). M-CHAT, audiology, developmental pediatrics."},

  // --- D119 expansion: Clinical Assessment (10 questions) ---
  {unit:"U5",topic:"Cardiac - Auscultation",type:"mc",q:"Where is the aortic valve best auscultated?",choices:["2nd left intercostal space at sternal border","2nd right intercostal space at sternal border","5th intercostal space at midclavicular line (apex)","4th left intercostal space at sternal border"],answer:1,explain:"Aortic valve: 2nd RICS (right intercostal space) at sternal border. Pulmonic: 2nd LICS. Tricuspid: 4th LICS. Mitral: 5th ICS at MCL (apex). Mnemonic: 'All Patients Take Meds' — Aortic, Pulmonic, Tricuspid, Mitral."},
  {unit:"U5",topic:"Cardiac - Murmurs",type:"mc",q:"A crescendo-decrescendo systolic murmur heard best at the 2nd right intercostal space radiating to the carotids. What is the most likely valvular lesion?",choices:["Mitral regurgitation","Aortic stenosis","Mitral stenosis","Aortic regurgitation"],answer:1,explain:"Aortic stenosis: crescendo-decrescendo systolic murmur, R 2nd ICS, radiates to carotids. Associated with syncope, angina, and heart failure. Severe AS: valve area <1.0 cm2. Aortic regurgitation is a diastolic murmur. Mitral regurgitation is holosystolic at apex radiating to axilla."},
  {unit:"U5",topic:"Pulmonary - Exam",type:"mc",q:"During pulmonary auscultation, you note increased tactile fremitus, dullness to percussion, and bronchial breath sounds over the right lower lobe. What does this indicate?",choices:["Pneumothorax","Pleural effusion","Consolidation (pneumonia)","COPD with hyperinflation"],answer:2,explain:"Consolidation: increased fremitus (sound transmits better through solid/liquid than air), dullness to percussion, bronchial breath sounds. Pneumothorax: decreased fremitus, hyperresonance, absent breath sounds. Pleural effusion: decreased fremitus, dullness, decreased breath sounds. COPD: decreased fremitus, hyperresonance, diminished breath sounds."},
  {unit:"U5",topic:"Abdominal - Exam Sequence",type:"mc",q:"What is the correct sequence for abdominal examination?",choices:["Palpation, percussion, auscultation, inspection","Inspection, auscultation, percussion, palpation","Auscultation, inspection, palpation, percussion","Inspection, palpation, percussion, auscultation"],answer:1,explain:"Abdominal exam: Inspection -> Auscultation -> Percussion -> Palpation. Auscultation BEFORE palpation because palpation can alter bowel sounds. Percussion assesses organ size and presence of fluid/gas. Palpation is last, starting with light palpation away from painful areas."},
  {unit:"U5",topic:"Neuro - Cranial Nerves",type:"mc",q:"A patient cannot shrug their shoulders against resistance and has difficulty turning their head. Which cranial nerve is affected?",choices:["CN IX (Glossopharyngeal)","CN X (Vagus)","CN XI (Spinal Accessory)","CN XII (Hypoglossal)"],answer:2,explain:"CN XI (Spinal Accessory): motor to sternocleidomastoid (head turning) and trapezius (shoulder shrug). CN IX: gag reflex, posterior pharynx sensation. CN X: palate elevation, gag reflex. CN XII: tongue movement (deviation toward side of lesion)."},
  {unit:"U5",topic:"Neuro - Reflexes",type:"mc",q:"A patient has hyperreflexia, positive Babinski sign, and spasticity in the right arm and leg. What does this pattern indicate?",choices:["Lower motor neuron lesion","Upper motor neuron lesion","Cerebellar lesion","Peripheral neuropathy"],answer:1,explain:"UMN lesion (corticospinal tract): hyperreflexia, spasticity, positive Babinski (upgoing toe), clonus. LMN lesion: hyporeflexia, flaccidity, fasciculations, atrophy. Cerebellar: ataxia, dysmetria, intention tremor. Peripheral neuropathy: stocking-glove sensory loss, diminished reflexes."},
  {unit:"U5",topic:"Dermatology - Lesion Description",type:"mc",q:"You note a flat, circumscribed, non-palpable area of color change less than 1cm on a patient's back. What is the correct dermatologic term?",choices:["Papule","Macule","Plaque","Nodule"],answer:1,explain:"Macule: flat, non-palpable, <1cm (e.g., freckle). Patch: flat, non-palpable, >1cm. Papule: raised, palpable, <1cm. Plaque: raised, palpable, >1cm. Nodule: deeper, solid, >1cm. Vesicle: fluid-filled, <1cm. Bulla: fluid-filled, >1cm."},
  {unit:"U5",topic:"Thyroid - Exam",type:"mc",q:"When examining the thyroid gland, what finding suggests a benign versus malignant nodule?",choices:["A single hard fixed nodule is more concerning for malignancy than a smooth mobile nodule","All thyroid nodules are benign","Size is the only determining factor","Tenderness confirms malignancy"],answer:0,explain:"Concerning features for thyroid malignancy: solitary nodule, hard consistency, fixation to surrounding tissue, rapid growth, hoarseness (recurrent laryngeal nerve involvement), cervical lymphadenopathy. Smooth, mobile, tender nodules are more likely benign (cyst, thyroiditis)."},
  {unit:"U5",topic:"Lymphatic - Exam",type:"mc",q:"A patient has a swollen, tender lymph node in the right anterior cervical chain. The node is warm, mobile, and 1.5cm. What is the most likely etiology?",choices:["Lymphoma","Metastatic cancer","Reactive lymphadenopathy (infection)","Tuberculosis"],answer:2,explain:"Tender, warm, mobile lymph nodes suggest acute infection/inflammation (reactive lymphadenopathy). Malignant nodes: non-tender, hard, fixed/matted, rubbery (lymphoma). TB: matted, can be tender, often cervical. Supraclavicular node (Virchow's node) = concerning for abdominal/thoracic malignancy."},
  {unit:"U5",topic:"Vital Signs - Pain",type:"mc",q:"The patient says their pain is '10 out of 10' but is calmly scrolling on their phone and laughing with a visitor. What is the most appropriate approach?",choices:["Document 'patient exaggerating' and ignore their pain score","Accept the patient's self-report of pain — pain is subjective and what the patient says it is","Confront the patient about inconsistency","Refuse to treat pain until objective signs are present"],answer:1,explain:"Pain is always subjective — 'Pain is whatever the experiencing person says it is, existing whenever they say it does' (McCaffery). The patient's self-report is the gold standard. Cultural, psychological, and behavioral factors influence pain expression. Treat the reported pain, not your judgment of the patient's behavior."},

  // --- D119 expansion: Clinical Examination (15 questions) ---
  {unit:"U5",topic:"Cardiac - Heart Sounds",type:"mc",q:"During cardiac auscultation, you hear a low-pitched diastolic rumble at the apex with the bell of the stethoscope, best heard in the left lateral decubitus position. What valvular lesion is most likely?",choices:["Mitral regurgitation","Mitral stenosis","Aortic stenosis","Tricuspid regurgitation"],answer:1,explain:"Mitral stenosis: low-pitched diastolic rumble at apex, best heard with bell in left lateral decubitus. Opening snap may precede the murmur. Often from rheumatic heart disease. Mitral regurgitation is a holosystolic murmur at apex radiating to axilla. Aortic stenosis is a systolic crescendo-decrescendo at right 2nd ICS."},
  {unit:"U5",topic:"Pulmonary - Breath Sounds",type:"mc",q:"During lung auscultation, you hear high-pitched, musical, continuous sounds predominantly during expiration. What is the correct term and what do these indicate?",choices:["Crackles (rales) — fluid in alveoli","Wheezes — narrowed airways (asthma, COPD, foreign body)","Rhonchi — secretions in large airways","Pleural friction rub — inflamed pleura"],answer:1,explain:"Wheezes: high-pitched, musical, continuous, predominantly expiratory. Indicate airway narrowing from bronchospasm, edema, mucus, or foreign body. Crackles: discontinuous, inspiratory (fine = interstitial, coarse = secretions). Rhonchi: low-pitched, snoring-like, may clear with cough. Pleural rub: leather-creaking, both phases."},
  {unit:"U5",topic:"Abdominal - Murphy Sign",type:"mc",q:"You press deeply in the right upper quadrant and ask the patient to take a deep breath. The patient experiences sudden pain and arrests inspiration. What is this sign and what does it indicate?",choices:["Rovsing sign — appendicitis","Murphy sign — acute cholecystitis","McBurney sign — appendicitis","Cullen sign — pancreatitis"],answer:1,explain:"Murphy sign: inspiratory arrest during deep RUQ palpation. Indicates acute cholecystitis (inflamed gallbladder descends onto examining hand). Rovsing sign: RLQ pain with LLQ palpation. McBurney sign: tenderness at McBurney point (2/3 from umbilicus to ASIS). Cullen sign: periumbilical ecchymosis (hemorrhagic pancreatitis)."},
  {unit:"U5",topic:"Neuro - Cranial Nerve II",type:"mc",q:"During a fundoscopic exam, you note blurred optic disc margins, venous engorgement, and absent venous pulsations bilaterally. What does this indicate?",choices:["Diabetic retinopathy","Papilledema — increased intracranial pressure","Hypertensive retinopathy","Normal variant"],answer:1,explain:"Papilledema: bilateral optic disc swelling from increased ICP. Key signs: blurred disc margins, venous engorgement, absent spontaneous venous pulsations, disc hyperemia. Unilateral disc swelling suggests optic neuritis or anterior ischemic optic neuropathy. Requires urgent neuroimaging to rule out mass, hydrocephalus, or idiopathic intracranial hypertension."},
  {unit:"U5",topic:"ENT - Otoscopic Exam",type:"mc",q:"During otoscopy, you see a retracted, amber-colored tympanic membrane with visible air-fluid levels and bubbles behind the membrane. The patient reports ear fullness and mild conductive hearing loss but no fever or pain. What is the diagnosis?",choices:["Acute otitis media","Otitis media with effusion (serous otitis)","Otitis externa","Tympanic membrane perforation"],answer:1,explain:"Otitis media with effusion (OME): retracted, amber TM with air-fluid levels or bubbles. No signs of acute infection (no fever, pain, or bulging). Caused by eustachian tube dysfunction. Common after URI or with allergies. Often self-resolving in 4-6 weeks. AOM has bulging, erythematous TM with pain and fever. Otitis externa has ear canal inflammation."},
  {unit:"U5",topic:"Dermatology - ABCDE",type:"mc",q:"A patient asks about a mole on their back. Which set of features is most concerning for melanoma using the ABCDE criteria?",choices:["Asymmetric, Border irregular, Color uniform, Diameter 2mm, Evolved over years","Asymmetric, Border irregular, Color variegated, Diameter 8mm, Evolving recently","Symmetric, Border regular, Color dark brown, Diameter 5mm, Stable","Asymmetric, Border regular, Color light, Diameter 3mm, New onset"],answer:1,explain:"ABCDE melanoma criteria: Asymmetry (one half unlike the other), Border irregularity (notched, ragged edges), Color variegation (multiple shades of brown/black/red/white/blue), Diameter >6mm (pencil eraser size), Evolution (changing in size, shape, color, or symptoms). Any ONE concerning feature warrants dermatology referral."},
  {unit:"U5",topic:"Lymphatic - Sentinel Node",type:"mc",q:"A patient with newly diagnosed breast cancer has a palpable firm, non-tender lymph node in the ipsilateral axilla. What is the most important next step in evaluating this node?",choices:["Reassure — likely reactive","Ultrasound with biopsy if abnormal architecture is seen","Start antibiotics for lymphadenitis","CT chest/abdomen/pelvis for staging before evaluating the node"],answer:1,explain:"Palpable axillary node in breast cancer: ultrasound first. Concerning features on US: loss of fatty hilum, cortical thickening >3mm, irregular borders, round shape (not oval). If abnormal: core needle biopsy or FNA. Pathologic node confirmation changes staging and treatment plan (neoadjuvant chemotherapy vs primary surgery)."},
  {unit:"U5",topic:"Breast - Exam Findings",type:"mc",q:"During a clinical breast exam, you note peau d'orange (skin thickening with prominent hair follicles resembling an orange peel) and nipple retraction in one breast. What is the most likely underlying pathology?",choices:["Fibrocystic breast changes","Inflammatory breast cancer","Fibroadenoma","Simple breast cyst"],answer:1,explain:"Peau d'orange + nipple retraction = inflammatory breast cancer until proven otherwise. Caused by tumor emboli blocking dermal lymphatics. Skin is warm, thickened, erythematous — can mimic mastitis but does NOT respond to antibiotics. Requires urgent biopsy. Fibrocystic changes present with lumpy, tender breasts. Fibroadenoma is a well-circumscribed, mobile, rubbery mass."},
  {unit:"U5",topic:"Vital Signs - Orthostatics",type:"mc",q:"You measure orthostatic vital signs on an elderly patient with dizziness. Supine BP 138/82, HR 72. Standing at 2 minutes: BP 108/70, HR 94. What do these findings indicate?",choices:["Normal orthostatic response","Orthostatic hypotension — systolic drop >20 mmHg with compensatory tachycardia","Hypertensive urgency","Vasovagal response"],answer:1,explain:"Orthostatic hypotension: systolic drop >=20 mmHg OR diastolic drop >=10 mmHg within 3 minutes of standing, with symptoms. Compensatory HR increase >15 bpm suggests volume depletion (not autonomic failure, where HR would not increase). Causes: dehydration, blood loss, medications (antihypertensives, diuretics), prolonged bed rest, autonomic neuropathy (diabetes, Parkinson)."},
  {unit:"U5",topic:"Abdominal - Rebound Tenderness",type:"mc",q:"During an abdominal exam, the patient has RLQ tenderness. You press deeply in the LLQ and the patient reports sharp pain in the RLQ. What is this sign and its significance?",choices:["Murphy sign — cholecystitis","Rovsing sign — peritoneal irritation, suggestive of appendicitis","Psoas sign — retroperitoneal inflammation","Obturator sign — pelvic appendicitis"],answer:1,explain:"Rovsing sign: RLQ pain elicited by LLQ palpation. Indicates peritoneal irritation and is associated with acute appendicitis. Psoas sign: RLQ pain with right hip extension against resistance (retrocecal appendix). Obturator sign: RLQ pain with internal rotation of flexed right hip (pelvic appendix). Rebound tenderness (Blumberg sign): pain upon rapid release of deep palpation."},
  {unit:"U5",topic:"Neuro - Mental Status",type:"mc",q:"You are screening a 72yo for cognitive impairment. They recall 1 of 3 words after 3 minutes and cannot draw a clock showing 10 past 11. What is the most appropriate screening tool and next step?",choices:["MMSE — if normal, no further evaluation","Mini-Cog — failed (1 word recall + abnormal clock draw), refer for comprehensive cognitive evaluation","MoCA — this test is not validated for cognitive screening","These findings are normal for age, no action needed"],answer:1,explain:"Mini-Cog: 3-word recall (0-3 points) + clock draw (normal/abnormal). Score 0-2 = positive screen (this patient: 1 word recall = 1 point + abnormal clock draw = 0 points = total 1, positive). Positive screen warrants comprehensive evaluation: detailed history, MMSE or MoCA, labs (TSH, B12), neuroimaging if indicated, and referral to neurology or geriatrics."},
  {unit:"U5",topic:"Vital Signs - Temperature",type:"mc",q:"A 92yo nursing home patient has a temperature of 97.8F but is confused, tachycardic, and hypotensive. The staff says 'she doesn't have a fever so it can't be sepsis.' What is the correct response?",choices:["Agree — no fever rules out sepsis","Elderly patients often have blunted fever response — infection and sepsis can present with normothermia or hypothermia","Check temperature rectally — oral temperatures are unreliable in elderly","Wait 4 hours and recheck temperature"],answer:1,explain:"Elderly patients have altered thermoregulation. Up to 30% of older adults with serious infections present without fever or with hypothermia. Confusion + tachycardia + hypotension in an elderly patient = sepsis until proven otherwise, regardless of temperature. Obtain cultures, lactate, start fluids and empiric antibiotics within 1 hour."},
  {unit:"U5",topic:"Pulmonary - Percussion",type:"mc",q:"You percuss the left posterior chest and note hyperresonance with decreased breath sounds and absent tactile fremitus. The trachea is deviated to the right. What is the most likely diagnosis?",choices:["Left-sided pleural effusion","Left-sided tension pneumothorax","Left lower lobe pneumonia","COPD exacerbation"],answer:1,explain:"Tension pneumothorax: hyperresonance, decreased/absent breath sounds, tracheal deviation AWAY from affected side (left pneumothorax → trachea deviates right). Requires immediate needle decompression (2nd ICS, midclavicular line) followed by chest tube. Pleural effusion: dullness to percussion, decreased breath sounds, no tracheal deviation. Pneumonia: dullness, bronchial breath sounds, increased fremitus."},
  {unit:"U5",topic:"Cardiac - JVP Assessment",type:"mc",q:"You assess jugular venous pressure with the patient at 45 degrees. The top of the venous pulsation is 5cm above the sternal angle. What is the estimated JVP and what does this indicate?",choices:["Normal JVP — 3 cm H2O","Elevated JVP — approximately 10 cm H2O, suggesting increased right atrial pressure (heart failure, volume overload, tamponade)","Low JVP — hypovolemia","JVP cannot be estimated without ultrasound"],answer:1,explain:"JVP estimation: add 5 cm (distance from sternal angle to right atrium, regardless of patient position) to the measured vertical height above sternal angle. Normal JVP <8 cm H2O. This patient: 5 + 5 = 10 cm H2O = elevated. Causes: right heart failure, volume overload, cardiac tamponade, constrictive pericarditis, tricuspid stenosis, pulmonary hypertension, SVC obstruction."},
  {unit:"U5",topic:"Neuro - Meningeal Signs",type:"mc",q:"A patient with fever and severe headache has positive Brudzinski sign (involuntary hip flexion with passive neck flexion) and positive Kernig sign (pain and resistance with knee extension while hip is flexed). What do these findings indicate?",choices:["Cervical spine injury","Meningeal irritation — strongly suggestive of meningitis","Sciatic nerve irritation","Normal findings in a febrile patient"],answer:1,explain:"Brudzinski and Kernig signs indicate meningeal irritation. In the setting of fever + headache = meningitis until proven otherwise. Do NOT delay antibiotics for lumbar puncture if meningitis is suspected. Obtain blood cultures, start empiric antibiotics (ceftriaxone + vancomycin + ampicillin if age extremes or immunocompromised) and dexamethasone, then perform LP when safe."}
];
