const D118_QUESTIONS = [
  // UNIT 2: Wellness & Health Promotion
  {unit:"U2",topic:"Evidence-Based Practice",type:"mc",q:"Which study design provides the highest level of evidence for clinical decision-making?",choices:["Case-control study","Cohort study","Randomized controlled trial","Cross-sectional study"],answer:2,explain:"RCTs are the gold standard — randomization controls for confounders and establishes causation."},
  {unit:"U2",topic:"Evidence-Based Practice",type:"mc",q:"A patient asks why you're using a specific treatment. You cite a systematic review of RCTs. What USPSTF grade would indicate high certainty of substantial benefit?",choices:["Grade B","Grade A","Grade C","Grade D"],answer:1,explain:"Grade A = high certainty of substantial net benefit. Grade B = high certainty of moderate benefit."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"At what age does the USPSTF recommend starting colorectal cancer screening for average-risk adults?",choices:["40 years","45 years","50 years","55 years"],answer:1,explain:"USPSTF updated recommendation in 2021: start at age 45 for average-risk adults."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"The USPSTF recommends abdominal aortic aneurysm (AAA) screening with one-time abdominal ultrasound for which group?",choices:["All adults over 65","Men 65-75 who have ever smoked","Women 65-75 who have ever smoked","Men and women 60-75 who have ever smoked"],answer:1,explain:"One-time ultrasound screening for men 65-75 who have ever smoked (at least 100 cigarettes). Not recommended for women."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"USPSTF recommends lung cancer screening with low-dose CT annually for adults aged 50-80 who have what smoking history?",choices:["10 pack-year history, current smoker","20 pack-year history, quit within 15 years OR current smoker","30 pack-year history, quit within 10 years OR current smoker","15 pack-year history, current smoker"],answer:2,explain:"USPSTF 2021: 50-80 years old, 20 pack-year history, currently smoke OR quit within past 15 years."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"Which screening is recommended by USPSTF for all adults regardless of risk factors?",choices:["Hepatitis B","Hepatitis C in adults 18-79","HIV in adults 15-65","Both B and C"],answer:3,explain:"Both Hepatitis C (18-79) and HIV (15-65) are Grade B recommendations for all adults in those age ranges."},
  {unit:"U2",topic:"Immunizations",type:"mc",q:"Which vaccines are recommended for ALL adults 19 years and older annually?",choices:["Influenza","Influenza and Tdap","Influenza and pneumococcal","Influenza and zoster"],answer:0,explain:"Influenza is the only vaccine recommended annually for ALL adults. Others have specific age/risk indications."},
  {unit:"U2",topic:"Immunizations",type:"mc",q:"At what age is the Shingrix (zoster) vaccine recommended?",choices:["50 years and older","60 years and older","65 years and older","55 years and older"],answer:0,explain:"Shingrix is recommended for adults 50 and older, given in 2 doses 2-6 months apart, even if prior Zostavax."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"USPSTF recommends depression screening for which adult population?",choices:["Adults 18+ with risk factors only","Adults 18+ with staff-assisted depression care support","All adults 18+","Adults 40+ only"],answer:2,explain:"USPSTF Grade B: Screen all adults 18+ for depression, including pregnant and postpartum women."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"At what interval should a Pap smear alone be done for women aged 21-65?",choices:["Every year","Every 2 years","Every 3 years","Every 5 years"],answer:2,explain:"Pap smear alone: every 3 years for women 21-65. Pap + HPV co-testing: every 5 years ages 30-65."},

  // UNIT 3: Acute Illness - EENT
  {unit:"U3",topic:"EENT",type:"mc",q:"A patient presents with unilateral eye redness, mucopurulent discharge, lid crusting, and no pain. Most likely diagnosis?",choices:["Viral conjunctivitis","Bacterial conjunctivitis","Allergic conjunctivitis","Iritis"],answer:1,explain:"Bacterial conjunctivitis: mucopurulent/purulent discharge, lid matting, typically unilateral to start. Treat with topical antibiotics."},
  {unit:"U3",topic:"EENT",type:"mc",q:"Which finding in a red eye warrants SAME-DAY ophthalmology referral?",choices:["Bilateral itching and watery discharge","Unilateral purulent discharge","Decreased visual acuity with eye pain","Seasonal exacerbation of redness"],answer:2,explain:"Decreased VA + eye pain = possible iritis, angle-closure glaucoma, or corneal ulcer — same-day referral required."},
  {unit:"U3",topic:"EENT",type:"mc",q:"A child presents with otalgia, fever, and TM with loss of landmarks, bulging, and erythema. First-line treatment?",choices:["Amoxicillin-clavulanate 90mg/kg/day","Amoxicillin 90mg/kg/day","Azithromycin","Watchful waiting for 48-72 hours in all children"],answer:1,explain:"AOM first-line: amoxicillin 90mg/kg/day (high dose) in children. Augmentin if recent antibiotics or conjunctivitis present."},
  {unit:"U3",topic:"EENT",type:"mc",q:"Treatment for allergic rhinitis — which is most effective as monotherapy?",choices:["Oral antihistamines","Intranasal antihistamines","Intranasal corticosteroids","Oral decongestants"],answer:2,explain:"Intranasal corticosteroids (fluticasone, mometasone) are the most effective single therapy for allergic rhinitis."},
  {unit:"U3",topic:"EENT",type:"mc",q:"A patient with 10 days of facial pressure, purulent nasal discharge, and maxillary toothache, not improving. Treatment?",choices:["Saline irrigation only","Amoxicillin 500mg TID x 5-7 days","Amoxicillin-clavulanate 875mg BID x 5-7 days","Azithromycin Z-pack"],answer:2,explain:"Acute bacterial rhinosinusitis: Amoxicillin-clavulanate is preferred. Amoxicillin alone if no recent antibiotics, mild, no risk factors."},

  // UNIT 3: Respiratory
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"A patient has cough, low-grade fever, wheezing after URI. CXR is normal. What is the most likely diagnosis?",choices:["Community acquired pneumonia","Acute bronchitis","Asthma exacerbation","Pertussis"],answer:1,explain:"Acute bronchitis: follows URI, cough 1-3 weeks, wheezing possible, normal CXR. Usually viral — antibiotics NOT indicated."},
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"A 65yo diabetic presents with fever, productive cough, RLL consolidation on CXR. PORT/PSI score suggests outpatient treatment. What is first-line treatment?",choices:["Azithromycin alone","Amoxicillin alone","Amoxicillin + azithromycin OR respiratory fluoroquinolone","IV ceftriaxone"],answer:2,explain:"CAP outpatient with comorbidities: combo beta-lactam + macrolide OR respiratory fluoroquinolone (levofloxacin, moxifloxacin)."},
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"What CURB-65 score indicates hospital admission is required for pneumonia?",choices:["Score of 1","Score of 2 or more","Score of 3 or more","Score of 4 or more"],answer:1,explain:"CURB-65: 0-1 = outpatient, 2 = consider admission, 3+ = hospitalize. Each point: Confusion, Urea>19, RR≥30, BP<90/60, age≥65."},

  // UNIT 3: GI Acute
  {unit:"U3",topic:"GI - Acute",type:"mc",q:"A patient presents with RLQ pain that began periumbilically, fever, nausea, and rebound tenderness. McBurney's point is tender. Next step?",choices:["Abdominal X-ray","CT abdomen/pelvis with contrast","Ultrasound abdomen","Start oral antibiotics and reassess"],answer:1,explain:"Appendicitis workup: CT abdomen/pelvis is gold standard in adults. Ultrasound preferred in children/pregnant women to avoid radiation."},
  {unit:"U3",topic:"GI - Acute",type:"mc",q:"Murphy's sign is positive (inspiratory arrest with RUQ palpation). Most likely diagnosis?",choices:["Appendicitis","Acute cholecystitis","Peptic ulcer disease","Pancreatitis"],answer:1,explain:"Murphy's sign = acute cholecystitis. Caused by RUQ palpation during inspiration when inflamed gallbladder descends onto examining hand."},

  // UNIT 4: Urinary/Renal
  {unit:"U4",topic:"Urinary - Acute",type:"mc",q:"An uncomplicated UTI in a non-pregnant woman. First-line treatment?",choices:["Ciprofloxacin 500mg BID x 3 days","Nitrofurantoin 100mg BID x 5 days","Trimethoprim-sulfamethoxazole DS BID x 7 days","Amoxicillin-clavulanate 875mg BID x 7 days"],answer:1,explain:"First-line for uncomplicated UTI: nitrofurantoin 5 days or TMP-SMX 3 days (if local resistance <20%). Fluoroquinolones are NOT first-line."},
  {unit:"U4",topic:"Urinary - Acute",type:"mc",q:"A woman with dysuria, flank pain, fever, CVA tenderness, nausea. Urinalysis shows WBCs, bacteria. Diagnosis and outpatient treatment?",choices:["UTI — nitrofurantoin x 5 days","Pyelonephritis — ciprofloxacin 500mg BID x 7 days","Pyelonephritis — TMP-SMX DS BID x 14 days","Pyelonephritis — amoxicillin-clavulanate x 14 days"],answer:1,explain:"Uncomplicated pyelonephritis outpatient: ciprofloxacin 500mg BID x 7 days OR TMP-SMX x 14 days if susceptible. Fluoro preferred for kidney penetration."},
  {unit:"U4",topic:"Renal",type:"mc",q:"A patient passes a kidney stone. Most common type of nephrolithiasis?",choices:["Struvite","Uric acid","Calcium oxalate","Cystine"],answer:2,explain:"80% of kidney stones are calcium oxalate. Struvite = infection stones. Uric acid = gout. Cystine = genetic disorder."},

  // UNIT 4: Dermatology
  {unit:"U4",topic:"Dermatology",type:"mc",q:"Honey-colored crusted lesions on a child's face around the nose/mouth. Most likely diagnosis and treatment?",choices:["Herpes labialis — acyclovir","Impetigo — mupirocin topical or amoxicillin-clavulanate","Contact dermatitis — topical steroids","Tinea faciei — clotrimazole"],answer:1,explain:"Impetigo: honey-crusted lesions, common in children, S. aureus or Strep. Localized: mupirocin topical. Widespread: oral antibiotics."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"A patient with well-demarcated, silvery-scaled plaques on elbows and knees. Most likely diagnosis?",choices:["Atopic dermatitis","Psoriasis","Tinea corporis","Seborrheic dermatitis"],answer:1,explain:"Psoriasis: silver-scaled plaques on extensor surfaces (elbows, knees, scalp). Nail pitting is also common."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"Dermatophyte infection of the nails (thickened, yellowed, crumbly nails). First-line oral treatment?",choices:["Fluconazole","Itraconazole","Terbinafine","Ketoconazole"],answer:2,explain:"Onychomycosis first-line oral: terbinafine (Lamisil) 250mg daily x 6 weeks (fingernails) or 12 weeks (toenails). Most effective with fewest drug interactions."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"A patient with intense nighttime itching, linear burrows between fingers, and similar symptoms in household contacts. Diagnosis and treatment?",choices:["Atopic dermatitis — triamcinolone cream","Scabies — permethrin 5% cream","Contact dermatitis — hydrocortisone","Pediculosis — permethrin 1% rinse"],answer:1,explain:"Scabies: Sarcoptes scabiei mite. Key features: nocturnal itching, burrows, household spread. Treat ALL household members with permethrin 5% from neck down."},

  // UNIT 5: Chronic Pulmonary
  {unit:"U5",topic:"Asthma",type:"mc",q:"A patient with asthma uses their rescue inhaler more than 2 days/week and wakes up with symptoms 3-4 nights/month. How is this classified?",choices:["Intermittent asthma","Mild persistent asthma","Moderate persistent asthma","Severe persistent asthma"],answer:1,explain:"Mild persistent: symptoms >2 days/week but not daily, nighttime awakenings 3-4x/month, minor limitation. Step 2 therapy: low-dose ICS."},
  {unit:"U5",topic:"Asthma",type:"mc",q:"What is the FIRST step in pharmacologic management of persistent asthma?",choices:["Add LABA","Start low-dose inhaled corticosteroid (ICS)","Start oral prednisone","Start montelukast"],answer:1,explain:"Step 2 (mild persistent): low-dose ICS is the cornerstone. LABAs are NEVER used as monotherapy in asthma — always with ICS."},
  {unit:"U5",topic:"COPD",type:"mc",q:"A 65yo smoker with FEV1/FVC <0.70 and FEV1 55% predicted. Which GOLD classification?",choices:["GOLD 1 — Mild","GOLD 2 — Moderate","GOLD 3 — Severe","GOLD 4 — Very severe"],answer:1,explain:"GOLD 2 (Moderate): FEV1 50-79% predicted. GOLD 1: ≥80%. GOLD 3: 30-49%. GOLD 4: <30%."},
  {unit:"U5",topic:"COPD",type:"mc",q:"Most important intervention shown to slow COPD progression?",choices:["Long-acting bronchodilators","Inhaled corticosteroids","Smoking cessation","Pulmonary rehabilitation"],answer:2,explain:"Smoking cessation is the ONLY intervention proven to slow decline in FEV1 and alter COPD progression. Everything else manages symptoms."},
  {unit:"U5",topic:"Pulmonary Embolism",type:"mc",q:"A patient with sudden dyspnea, pleuritic chest pain, tachycardia, and recent long flight. What is the FIRST diagnostic test?",choices:["V/Q scan","CT pulmonary angiography (CTPA)","D-dimer if low pretest probability","Chest X-ray"],answer:2,explain:"Use Wells criteria first. If low pretest probability → D-dimer. If elevated → CTPA. CTPA is gold standard but D-dimer can rule out in low-probability patients."},

  // UNIT 5: Chronic Cardiovascular
  {unit:"U5",topic:"Hypertension",type:"mc",q:"A 55yo with BP 145/92 on two separate visits. No other comorbidities. ACC/AHA stage?",choices:["Elevated BP","Stage 1 HTN","Stage 2 HTN","Hypertensive urgency"],answer:1,explain:"ACC/AHA 2017: Stage 1 HTN = 130-139/80-89. Stage 2 = ≥140/90. First-line lifestyle changes ± medication based on CVD risk."},
  {unit:"U5",topic:"Hypertension",type:"mc",q:"A diabetic patient with HTN and CKD. What is the preferred antihypertensive class?",choices:["Calcium channel blockers","Beta-blockers","ACE inhibitor or ARB","Thiazide diuretics"],answer:2,explain:"ACE inhibitors or ARBs are preferred in diabetics with HTN and CKD due to nephroprotective effects (reduce proteinuria, slow GFR decline)."},
  {unit:"U5",topic:"Heart Failure",type:"mc",q:"A patient with dyspnea on exertion, orthopnea, and bilateral crackles. Echo shows EF of 35%. What is the diagnosis?",choices:["HFpEF","HFrEF","Diastolic dysfunction only","Cor pulmonale"],answer:1,explain:"HFrEF (Heart Failure with reduced EF): EF <40%. HFpEF: EF ≥50%. Treatment differs significantly — ACE/ARB + beta-blocker + aldosterone antagonist for HFrEF."},
  {unit:"U5",topic:"Heart Failure",type:"mc",q:"NYHA Class III heart failure is defined as?",choices:["No symptoms","Symptoms with moderate exertion, slight limitation","Symptoms with less than ordinary activity, marked limitation","Symptoms at rest"],answer:2,explain:"NYHA Class III: marked limitation — comfortable only at rest, symptoms with less than ordinary activity. Class II = slight limitation. Class IV = symptoms at rest."},
  {unit:"U5",topic:"CAD",type:"mc",q:"A patient with stable angina has CCS Class II. What does this mean?",choices:["No angina","Angina with ordinary activity, slight limitation","Angina with less than ordinary activity, marked limitation","Angina at rest"],answer:1,explain:"CCS Class II: slight limitation — angina with ordinary exertion (walking >2 blocks, climbing >1 flight). Class I = no ordinary activity limitation."},

  // UNIT 5: Chronic GI
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"Most common cause of peptic ulcer disease?",choices:["NSAID use","H. pylori infection","Stress","Alcohol use"],answer:1,explain:"H. pylori causes ~70% of duodenal ulcers and ~50% of gastric ulcers. NSAIDs are second most common. Test and treat H. pylori first."},
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"First-line treatment for H. pylori eradication?",choices:["Omeprazole + amoxicillin","Clarithromycin triple therapy (PPI + clarithromycin + amoxicillin)","Quadruple therapy (PPI + bismuth + metronidazole + tetracycline)","PPI monotherapy"],answer:2,explain:"Clarithromycin triple therapy 14 days if local clarithromycin resistance <15%. Quadruple therapy preferred in high-resistance areas or prior macrolide exposure."},
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"IBS diagnostic criteria (Rome IV): recurrent abdominal pain at least how often, associated with defecation or stool changes?",choices:["Once a month for 3 months","Once a week for 3 months","Daily for 1 month","Twice a week for 6 months"],answer:1,explain:"Rome IV IBS criteria: recurrent abdominal pain ≥1 day/week for 3 months, associated with 2+ of: related to defecation, change in stool frequency, change in stool form."},

  // UNIT 6: Chronic MSK & Rheumatic
  {unit:"U6",topic:"MSK - Chronic",type:"mc",q:"A patient with first MTP joint swelling, severe acute pain, and serum uric acid of 9.2. Synovial fluid shows negatively birefringent needle-shaped crystals. Diagnosis?",choices:["Pseudogout","Septic arthritis","Gout","Rheumatoid arthritis"],answer:2,explain:"Gout: negatively birefringent needle-shaped monosodium urate crystals. Pseudogout: positively birefringent rhomboid calcium pyrophosphate crystals."},
  {unit:"U6",topic:"MSK - Chronic",type:"mc",q:"First-line treatment for acute gout flare?",choices:["Allopurinol","Colchicine or NSAIDs","Prednisone only","Febuxostat"],answer:1,explain:"Acute gout: NSAIDs (indomethacin), colchicine, or steroids. Allopurinol and febuxostat are for PREVENTION — do NOT start during an acute attack."},
  {unit:"U6",topic:"Rheumatic",type:"mc",q:"A woman with malar rash, photosensitivity, oral ulcers, positive ANA and anti-dsDNA antibodies, thrombocytopenia. Diagnosis?",choices:["Rheumatoid arthritis","Dermatomyositis","Systemic lupus erythematosus","Sjogren syndrome"],answer:2,explain:"SLE: malar rash, photosensitivity, oral ulcers, serositis, renal, neuro, hematologic, immunologic (ANA, anti-dsDNA, anti-Sm). 4/11 criteria needed."},
  {unit:"U6",topic:"Rheumatic",type:"mc",q:"A 70yo woman with bilateral shoulder/hip girdle pain, stiffness worse in the morning, ESR >50. What diagnosis to consider first?",choices:["Fibromyalgia","Polymyalgia rheumatica","RA","Giant cell arteritis"],answer:1,explain:"PMR: older adults, bilateral proximal muscle pain/stiffness, elevated ESR/CRP, dramatic response to low-dose prednisone. Always rule out giant cell arteritis (temporal arteritis)."},

  // UNIT 6: Chronic Neurologic
  {unit:"U6",topic:"Neurology",type:"mc",q:"Classic triad of Parkinson's disease?",choices:["Tremor, rigidity, postural instability","Tremor, chorea, dementia","Rigidity, spasticity, clonus","Bradykinesia, tremor, rigidity"],answer:3,explain:"Parkinson's triad: resting tremor (pill-rolling), rigidity (cogwheel), bradykinesia. Plus postural instability. Dopaminergic neuron loss in substantia nigra."},
  {unit:"U6",topic:"Neurology",type:"mc",q:"A 40yo woman with relapsing-remitting neurologic symptoms, optic neuritis, Lhermitte's sign, and MRI white matter plaques. Diagnosis?",choices:["ALS","Guillain-Barre syndrome","Multiple sclerosis","Myasthenia gravis"],answer:2,explain:"MS: demyelinating disease, young adults (F>M), relapsing-remitting, optic neuritis, Lhermitte's sign, periventricular white matter lesions on MRI."},
  {unit:"U6",topic:"Neurology",type:"mc",q:"Migraine with aura vs without aura — what characterizes aura?",choices:["Nausea and vomiting","Phonophobia","Fully reversible neurologic symptoms lasting 5-60 min","Unilateral throbbing pain"],answer:2,explain:"Migraine aura: fully reversible neurologic symptoms (visual, sensory, speech) developing over ≥5 min, lasting 5-60 min, followed by headache within 60 min."},

  // UNIT 7: Endocrine/Metabolic
  {unit:"U7",topic:"Diabetes",type:"mc",q:"Diagnostic criteria for Type 2 Diabetes Mellitus (any ONE of these). Which is correct?",choices:["Fasting glucose ≥110 mg/dL","HbA1c ≥6.5%","2-hour glucose ≥180 mg/dL on OGTT","Random glucose ≥180 with symptoms"],answer:1,explain:"DM diagnosis: FBG ≥126, HbA1c ≥6.5%, 2hr OGTT ≥200, OR random glucose ≥200 with symptoms. Prediabetes: FBG 100-125, HbA1c 5.7-6.4%."},
  {unit:"U7",topic:"Diabetes",type:"mc",q:"First-line medication for Type 2 DM with no contraindications?",choices:["Insulin","GLP-1 agonist","Metformin","SGLT-2 inhibitor"],answer:2,explain:"Metformin is first-line for T2DM unless contraindicated (eGFR <30, contrast dye, etc.). Add-ons depend on comorbidities — GLP-1 or SGLT-2 if CVD/HF/CKD."},
  {unit:"U7",topic:"Thyroid",type:"mc",q:"A patient with fatigue, cold intolerance, weight gain, constipation, bradycardia, and dry skin. TSH is elevated, free T4 is low. Diagnosis and treatment?",choices:["Hyperthyroidism — methimazole","Hypothyroidism — levothyroxine","Subclinical hypothyroidism — monitor only","Hashimoto's thyroiditis — selenium"],answer:1,explain:"Primary hypothyroidism: high TSH, low free T4. Most common cause = Hashimoto's (autoimmune). Treatment: levothyroxine, adjust dose to normalize TSH."},
  {unit:"U7",topic:"Thyroid",type:"mc",q:"A patient with heat intolerance, weight loss, tremor, palpitations, diarrhea, exophthalmos, and diffuse goiter. TSH is suppressed. Diagnosis?",choices:["Toxic multinodular goiter","Graves' disease","Thyroid storm","De Quervain thyroiditis"],answer:1,explain:"Graves' disease: most common hyperthyroidism, autoimmune (TSH receptor antibodies), exophthalmos (pathognomonic), diffuse goiter, pretibial myxedema."},

  // UNIT 7: Mental Health
  {unit:"U7",topic:"Mental Health",type:"mc",q:"A patient meets criteria for Major Depressive Disorder. First-line pharmacotherapy?",choices:["Bupropion","Tricyclic antidepressant (TCA)","SSRI","Benzodiazepine"],answer:2,explain:"SSRIs are first-line for MDD due to efficacy and tolerability profile. SNRIs are also acceptable. TCAs and MAOIs are second/third line due to side effect profiles."},
  {unit:"U7",topic:"Mental Health",type:"mc",q:"DSM-5 criteria for MDD requires how many symptoms for at least how many weeks?",choices:["3 symptoms for 1 week","5 symptoms for 2 weeks","4 symptoms for 2 weeks","5 symptoms for 1 month"],answer:1,explain:"MDD: 5+ symptoms for ≥2 weeks, including depressed mood OR anhedonia. Symptoms: sleep, interest, guilt, energy, concentration, appetite, psychomotor, suicidality."},
  {unit:"U7",topic:"Mental Health",type:"mc",q:"A patient on an SSRI for 4 weeks reports little improvement. What is the appropriate next step?",choices:["Switch to a TCA immediately","Increase dose if at submaximal dosing or switch after adequate trial (6-8 weeks)","Add a benzodiazepine","Add lithium augmentation"],answer:1,explain:"Adequate antidepressant trial = 6-8 weeks at therapeutic dose. At 4 weeks with no response: ensure therapeutic dosing. Full trial before switching."},

  // CASE SCENARIOS
  {unit:"U5",topic:"Cardiovascular - Case",type:"case",q:"A 58yo male smoker with DM and HTN presents with 20 min of substernal chest pressure radiating to left arm, diaphoresis, and nausea. BP 155/95, HR 100. EKG shows ST elevation in leads II, III, aVF. What is the most likely diagnosis and immediate management priority?",choices:["NSTEMI — start heparin and schedule cath within 24-72 hrs","Inferior STEMI — activate cath lab, aspirin 325mg, heparin, call EMS transfer","Stable angina — nitroglycerine and discharge with stress test","Unstable angina — admit for monitoring"],answer:1,explain:"ST elevation in II, III, aVF = inferior STEMI (RCA). Time is muscle — activate cath lab immediately. Aspirin 325mg chewed, heparin, O2 if hypoxic, nitroglycerin (CAUTION in inferior MI — may cause hypotension if RV involved)."},
  {unit:"U3",topic:"Respiratory - Case",type:"case",q:"A 72yo nursing home patient with fever 102, HR 110, RR 24, BP 105/70, O2 sat 88% on room air, and left lower lobe infiltrate on CXR. CURB-65 score = 4. Best next step?",choices:["Discharge with oral levofloxacin","Admit to general floor with IV antibiotics","ICU admission given score and hemodynamics","Start azithromycin and recheck in 48 hours"],answer:2,explain:"CURB-65 of 4 + hemodynamic instability (hypotension, tachycardia) + O2 sat 88% = severe CAP requiring ICU-level care. IV broad-spectrum antibiotics, respiratory support."},
  {unit:"U7",topic:"Diabetes - Case",type:"case",q:"A 52yo with T2DM, HTN, and established ASCVD (prior MI) presents for medication management. HbA1c is 8.2%. They are on metformin. What medication should be added given their cardiovascular history?",choices:["Add sulfonylurea (glipizide)","Add GLP-1 agonist (semaglutide or liraglutide) with proven CV benefit","Add DPP-4 inhibitor (sitagliptin)","Add insulin glargine"],answer:1,explain:"ADA guidelines: T2DM + established ASCVD -> add GLP-1 RA (semaglutide, liraglutide) OR SGLT-2 inhibitor with proven CV benefit regardless of HbA1c. Reduces MACE."},

  // ============================================================
  // TARGETED WEAK-AREA QUESTIONS — MSK (8), Endocrine (7), ENT (5)
  // Added Jun 25, 2026
  // ============================================================

  // --- MSK (8 questions) ---
  {unit:"U3",topic:"MSK - Osteoarthritis",type:"mc",q:"A 62yo woman reports bilateral knee pain that worsens with activity and improves with rest. Morning stiffness lasts 15 minutes. No erythema or warmth. X-ray shows joint space narrowing and osteophytes. First-line pharmacologic treatment?",choices:["Oral prednisone","Acetaminophen and/or topical NSAIDs","Methotrexate","Allopurinol"],answer:1,explain:"OA first-line: acetaminophen, topical NSAIDs (diclofenac gel), or oral NSAIDs if topical fails. Joint space narrowing + osteophytes on X-ray confirm OA. No inflammatory signs (stiffness <30 min, no warmth) distinguishes from RA."},
  {unit:"U3",topic:"MSK - Rheumatoid Arthritis",type:"mc",q:"A 45yo woman has bilateral MCP and PIP joint swelling, morning stiffness lasting 2 hours, and fatigue. She has subcutaneous nodules on her forearms. Which lab finding is most specific for this condition?",choices:["Elevated ESR","Positive ANA","Anti-CCP antibodies","Elevated CRP"],answer:2,explain:"Anti-CCP (anti-citrullinated protein antibody) is >95% specific for RA. Rheumatoid factor is less specific. ESR and CRP are non-specific inflammatory markers. ANA is more associated with SLE."},
  {unit:"U3",topic:"MSK - Gout",type:"mc",q:"A 55yo man presents with acute-onset severe pain, erythema, and swelling in the first MTP joint. Serum uric acid is 9.2 mg/dL. What is the first-line treatment for this acute attack?",choices:["Allopurinol","Febuxostat","NSAIDs, colchicine, or corticosteroids","Probenecid"],answer:2,explain:"Acute gout: treat the inflammation first (NSAIDs, colchicine, or corticosteroids). Do NOT start urate-lowering therapy (allopurinol, febuxostat) during an acute flare — it can prolong the attack. Start ULT 2-4 weeks after flare resolves."},
  {unit:"U3",topic:"MSK - Fibromyalgia",type:"mc",q:"A 38yo woman reports 6 months of widespread body pain, fatigue, unrefreshing sleep, and cognitive difficulty. Physical exam is unremarkable. Labs are normal. What is the most appropriate initial management?",choices:["Opioid analgesics","Prednisone taper","Low-impact exercise, sleep hygiene, and possible duloxetine or pregabalin","Referral for rheumatology biopsy"],answer:2,explain:"Fibromyalgia diagnosis: widespread pain >3 months + fatigue/sleep/cognitive symptoms, normal exam and labs. No diagnostic test. Treatment: patient education, aerobic exercise, CBT, sleep hygiene. Pharmacologic: duloxetine (SNRI), pregabalin, or milnacipran. Opioids and steroids are NOT indicated."},
  {unit:"U3",topic:"MSK - Low Back Pain",type:"mc",q:"A 40yo construction worker reports acute low back pain after lifting. No radicular symptoms, no bowel/bladder changes, no red flags. Straight leg raise is negative. What is the most appropriate initial management?",choices:["Immediate MRI of lumbar spine","Bed rest for 2 weeks","Continue normal activity as tolerated, NSAIDs, and heat","Referral for epidural steroid injection"],answer:2,explain:"Acute non-specific low back pain without red flags: continue activity as tolerated, avoid bed rest beyond 1-2 days. NSAIDs, heat, and patient reassurance. MRI is NOT indicated without red flags (cauda equina, infection, fracture, cancer). Most cases resolve within 4-6 weeks."},
  {unit:"U3",topic:"MSK - Rotator Cuff",type:"mc",q:"A 55yo painter has shoulder pain that worsens with overhead activity and at night. On exam, he has weakness with empty-can test and painful arc between 60-120 degrees of abduction. Most likely diagnosis?",choices:["Adhesive capsulitis (frozen shoulder)","Rotator cuff tendinopathy or tear","Glenohumeral osteoarthritis","AC joint separation"],answer:1,explain:"Rotator cuff pathology: painful arc (60-120 degrees), positive empty-can test (supraspinatus), positive Hawkins test (impingement), night pain, occupational overuse. Adhesive capsulitis shows global ROM loss (passive AND active). AC joint: pain at top of shoulder, positive cross-body test."},
  {unit:"U3",topic:"MSK - Carpal Tunnel",type:"mc",q:"A 35yo pregnant woman in third trimester reports bilateral hand numbness and tingling in the thumb, index, and middle fingers, worse at night. Phalen's test reproduces symptoms. What is the most appropriate initial management?",choices:["Immediate carpal tunnel release surgery","Oral corticosteroids","Wrist splinting in neutral position (especially at night)","Gabapentin"],answer:2,explain:"Carpal tunnel in pregnancy: nocturnal wrist splints (neutral position) are first-line. Symptoms typically resolve postpartum. Phalen's test (wrist flexion for 60 sec reproducing symptoms) and Tinel's sign support diagnosis. Median nerve distribution (thumb, index, middle, radial half of ring finger)."},
  {unit:"U3",topic:"MSK - Osteoporosis",type:"mc",q:"A 68yo postmenopausal woman with no prior fractures has a DEXA scan showing T-score -2.7 at the lumbar spine. She has no secondary causes. What is the first-line pharmacologic treatment?",choices:["Calcium and vitamin D supplementation alone","Oral bisphosphonate (alendronate)","Calcitonin nasal spray","Teriparatide"],answer:1,explain:"Osteoporosis treatment: T-score <= -2.5 OR fragility fracture = treat. First-line: oral bisphosphonate (alendronate 70mg weekly). Ensure adequate calcium (1200mg/day) and vitamin D (800-1000 IU/day). Teriparatide reserved for severe osteoporosis or bisphosphonate failure. Calcitonin is third-line."},

  // --- Endocrine (7 questions) ---
  {unit:"U7",topic:"Diabetes - Management",type:"mc",q:"A 58yo with T2DM on metformin has HbA1c 8.4%. eGFR is 45 mL/min. What medication should be AVOIDED or used with caution due to reduced renal function?",choices:["Empagliflozin (SGLT-2 inhibitor)","Semaglutide (GLP-1 agonist)","Pioglitazone","Insulin glargine"],answer:0,explain:"SGLT-2 inhibitors require eGFR >= 20-30 mL/min for initiation depending on the agent. Empagliflozin: do not initiate if eGFR <20. Reduced efficacy with declining renal function. GLP-1 agonists, pioglitazone, and insulin can be used with renal adjustment."},
  {unit:"U7",topic:"Thyroid - Hypothyroidism",type:"mc",q:"A 45yo woman with fatigue, weight gain, and cold intolerance has TSH 12.5 mIU/L and free T4 0.6 ng/dL (both abnormal). What is the appropriate treatment and monitoring?",choices:["Liothyronine (T3) 25mcg daily, recheck TSH in 6 months","Levothyroxine 1.6 mcg/kg/day, recheck TSH in 6-8 weeks","Methimazole 10mg daily","Observation and repeat labs in 6 months"],answer:1,explain:"Primary hypothyroidism: elevated TSH + low free T4 = start levothyroxine. Starting dose 1.6 mcg/kg/day (full replacement) or 25-50mcg in elderly/cardiac patients. Recheck TSH in 6-8 weeks. Liothyronine (T3) is NOT first-line. Methimazole treats hyperthyroidism."},
  {unit:"U7",topic:"Thyroid - Hyperthyroidism",type:"mc",q:"A 32yo woman presents with palpitations, tremor, heat intolerance, and 15lb weight loss. She has diffuse, non-tender goiter and exophthalmos. TSH is undetectable, free T4 is elevated. What is the most likely diagnosis?",choices:["Toxic multinodular goiter","Graves disease","Subacute thyroiditis","Thyroid adenoma"],answer:1,explain:"Graves disease: diffuse goiter + exophthalmos + hyperthyroid labs (suppressed TSH, elevated T4) in a young woman. Caused by TSH receptor antibodies (TRAb). Treatment: methimazole (preferred over PTU), beta-blockers for symptoms, consider radioactive iodine or thyroidectomy for definitive treatment."},
  {unit:"U7",topic:"Endocrine - Adrenal",type:"mc",q:"A patient on long-term prednisone for polymyalgia rheumatica presents for a routine visit. They are on 20mg daily for 3 months and you plan to taper. What is the most important risk to counsel about if the taper is too rapid?",choices:["Rebound inflammation of PMR","Adrenal insufficiency (secondary adrenal suppression)","Cushingoid withdrawal syndrome","Hyperkalemia"],answer:1,explain:"Prolonged exogenous corticosteroids suppress the HPA axis, causing secondary adrenal insufficiency. Tapering too quickly prevents adrenal recovery. Adrenal crisis (hypotension, shock) can occur with abrupt withdrawal. Taper slowly over weeks to months. Stress-dose steroids may be needed for illness/surgery."},
  {unit:"U7",topic:"Diabetes - Screening",type:"mc",q:"A 48yo asymptomatic woman with BMI 32 and family history of T2DM in her mother asks about diabetes screening. She had GDM during her last pregnancy 3 years ago. What is the appropriate screening recommendation?",choices:["Fasting glucose only","Screen now with HbA1c or fasting glucose; if normal, repeat every 3 years","No screening needed until age 55","Screen only if she develops symptoms"],answer:1,explain:"USPSTF: screen adults 35-70 who are overweight/obese for T2DM. History of GDM increases risk further. HbA1c >= 6.5%, fasting glucose >= 126, or 2hr OGTT >= 200 confirms diagnosis. Repeat every 1-3 years if normal. Screen earlier/more frequently with GDM history."},
  {unit:"U7",topic:"Endocrine - Obesity",type:"mc",q:"A 42yo with BMI 34, HTN, and prediabetes (HbA1c 6.1%) has tried lifestyle modification for 6 months with only 4% weight loss. What pharmacologic option is most appropriate to consider?",choices:["Phentermine alone indefinitely","GLP-1 agonist (semaglutide) approved for weight management","Orlistat and metformin combination","Immediate bariatric surgery referral"],answer:1,explain:"Weight loss pharmacotherapy: BMI >= 30 OR BMI >= 27 with comorbidities. GLP-1 agonists (semaglutide 2.4mg, liraglutide 3mg) are FDA-approved for chronic weight management. Phentermine is short-term only (12 weeks). Bariatric surgery: BMI >= 35 with comorbidity OR BMI >= 40."},
  {unit:"U7",topic:"Endocrine - Metabolic Syndrome",type:"mc",q:"A patient has waist circumference 42 inches, fasting glucose 108 mg/dL, BP 138/88, HDL 34 mg/dL, and triglycerides 210 mg/dL. How many ATP III criteria for metabolic syndrome does this patient meet?",choices:["2 criteria","3 criteria","4 criteria","5 criteria"],answer:3,explain:"Meets all 5 ATP III criteria: (1) waist >40 inches in men, (2) fasting glucose >=100 mg/dL, (3) BP >=130 mmHg systolic, (4) HDL <40 mg/dL in men, (5) triglycerides >=150 mg/dL. Patient meets every single criterion. Metabolic syndrome = any 3 of the 5."},

  // --- ENT (5 questions) ---
  {unit:"U3",topic:"EENT - Pharyngitis",type:"mc",q:"A 15yo presents with sore throat, fever 102F, tender anterior cervical lymphadenopathy, tonsillar exudates, and no cough. What is the appropriate management?",choices:["Amoxicillin empirically without testing","Rapid strep test; if positive, treat with penicillin or amoxicillin","Symptomatic treatment only — most pharyngitis is viral","Azithromycin empirically"],answer:1,explain:"Centor criteria: fever, tender anterior cervical nodes, tonsillar exudates, no cough, age 3-14. Score >= 3: test for GAS (rapid strep or culture). Treat if positive: penicillin V or amoxicillin x 10 days (or one-dose IM benzathine penicillin). Antibiotics prevent rheumatic fever, reduce symptoms by ~1 day."},
  {unit:"U3",topic:"EENT - Sinusitis",type:"mc",q:"A patient has 12 days of facial pressure, purulent nasal discharge, maxillary tooth pain, and no improvement after initial symptomatic treatment. What is the most appropriate next step?",choices:["Continue symptomatic treatment for another week","Obtain CT sinus","Start amoxicillin-clavulanate","Start oxymetazoline nasal spray for 14 days"],answer:2,explain:"Acute bacterial rhinosinusitis criteria: symptoms >10 days without improvement OR double-worsening (improvement then worsening). First-line antibiotic: amoxicillin-clavulanate. CT sinus is NOT indicated for uncomplicated ABRS — reserved for recurrent or complicated cases. Topical decongestants limited to 3 days to avoid rhinitis medicamentosa."},
  {unit:"U3",topic:"EENT - Otitis Media",type:"mc",q:"A 2yo presents with ear pain, fever 102F, and bulging, erythematous TM with loss of landmarks. The child attends daycare and has had 2 prior AOM episodes. What is the first-line antibiotic and duration?",choices:["Amoxicillin 45mg/kg/day x 5 days","Amoxicillin 90mg/kg/day x 10 days","Amoxicillin-clavulanate 90mg/kg/day x 10 days","Azithromycin x 5 days"],answer:2,explain:"AOM in child with recent antibiotic exposure, daycare attendance, or recurrent AOM: amoxicillin-clavulanate 90mg/kg/day (amox component) x 10 days. Amoxicillin 90mg/kg/day x 10 days is first-line for uncomplicated AOM without risk factors. Azithromycin reserved for penicillin allergy. Shorter courses (5-7 days) for children >=2 with mild disease."},
  {unit:"U3",topic:"EENT - Allergic Rhinitis",type:"mc",q:"A patient with seasonal sneezing, clear rhinorrhea, and itchy eyes every spring for 3 years asks about the most effective long-term treatment. What do you recommend?",choices:["Oral cetirizine as needed","Intranasal fluticasone daily during allergy season","Oral pseudoephedrine during symptoms","Montelukast as first-line therapy"],answer:1,explain:"Intranasal corticosteroids (fluticasone, mometasone, triamcinolone) are the most effective monotherapy for allergic rhinitis. Start before allergy season begins for best results. Oral antihistamines help acute symptoms but are less effective for congestion. Montelukast is second-line (especially if concurrent asthma). Decongestants limited to short-term use."},
  {unit:"U3",topic:"EENT - Hearing Loss",type:"mc",q:"A 72yo reports gradual, bilateral hearing loss over several years, worse in noisy environments. He says people mumble more than they used to. Weber test: lateralizes equally. Rinne test: AC > BC bilaterally. What is the most likely diagnosis and management?",choices:["Conductive hearing loss — refer for stapedectomy","Presbycusis (sensorineural hearing loss) — audiometry and consider hearing aids","Meniere disease — start low-salt diet and meclizine","Acoustic neuroma — order MRI brain"],answer:1,explain:"Presbycusis: age-related, bilateral, gradual high-frequency SNHL. Speech discrimination worse in noise. Normal Rinne (AC > BC) and midline Weber confirm sensorineural. Management: audiometry, hearing aids, communication strategies. Meniere disease has vertigo + tinnitus + fluctuating SNHL. Acoustic neuroma is typically unilateral with tinnitus/vertigo."},

  // ============================================================
  // MED STUDENT NOTES INTEGRATION — 20 questions from PDF content
  // Endocrine (10), MSK (6), Respiratory (4)
  // Added Jun 25, 2026
  // ============================================================

  // --- Endocrine: Diabetes (4 questions, sourced from Endocrine System.pdf pp 125-141) ---
  {unit:"U7",topic:"Diabetes - DKA",type:"mc",q:"A 22yo with T1DM presents with nausea, vomiting, abdominal pain, and fruity-smelling breath. Glucose is 22 mmol/L, pH 7.1, bicarbonate 10 mmol/L. What is the primary pathophysiological process causing this presentation?",choices:["Excess insulin causing hypoglycemia","Absolute insulin deficiency leading to ketone production and metabolic acidosis","Insulin resistance with hyperosmolar state","Pancreatic beta-cell hyperplasia"],answer:1,explain:"DKA: absolute insulin deficiency causes cells to switch to fat metabolism, producing ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone). This produces the fruity (acetone) breath, metabolic acidosis (low pH, low bicarb), and hyperglycemia. DKA is primarily a Type 1 diabetes complication. Hyperosmolar hyperglycemic state (HHS) is more common in Type 2 and lacks significant ketosis."},
  {unit:"U7",topic:"Diabetes - T2DM Pathogenesis",type:"mc",q:"A 52yo obese patient with T2DM has increasing insulin requirements over 5 years. What best explains the progressive nature of their disease?",choices:["Autoimmune beta-cell destruction accelerates","Insulin resistance increases while beta-cell function progressively declines","Exogenous insulin causes antibody formation","Metformin loses efficacy in all patients after 5 years"],answer:1,explain:"T2DM is progressive: over time, insulin resistance increases AND beta-cell function declines. Obesity is the #1 predisposer of insulin resistance due to adipokine release (resistin, leptin, adiponectin). Later stages require more intensive treatment. This differs from T1DM which is autoimmune beta-cell destruction."},
  {unit:"U7",topic:"Diabetes - Metabolic Syndrome",type:"mc",q:"A 48yo male has waist 44 inches, BP 142/92, fasting glucose 112 mg/dL, HDL 32 mg/dL, triglycerides 180 mg/dL. Which metabolic syndrome component is measured INCORRECTLY for ATP III criteria?",choices:["Waist circumference — should be measured at umbilicus, not iliac crest","Blood pressure — should use diastolic only","HDL — level is actually protective, not a risk factor","All measurements are correct for ATP III criteria"],answer:0,explain:"ATP III waist circumference: measured at the iliac crest (top of hip bone), NOT at the umbilicus. Cutoffs: >40 inches in men, >35 inches in women. This patient meets all 5 criteria regardless, but the measurement technique matters. Other criteria: fasting glucose >=100, BP >=130/>=85, HDL <40 men/<50 women, TG >=150."},
  {unit:"U7",topic:"Diabetes - Somogyi Effect",type:"mc",q:"A T1DM patient reports morning hyperglycemia despite increasing their bedtime insulin dose. You suspect the Somogyi effect. What is the underlying mechanism?",choices:["Dawn phenomenon — circadian cortisol surge causing morning hyperglycemia","Nocturnal hypoglycemia triggering counter-regulatory hormone release (glucagon, adrenaline, cortisol) causing rebound hyperglycemia","Insufficient basal insulin leading to overnight glucose rise","Late-night carbohydrate snacking"],answer:1,explain:"Somogyi effect: circadian elevations in counter-regulatory hormones (GH, cortisol) cause early-morning hyperglycemia -> patient increases bedtime insulin -> sustained nocturnal hypoglycemia -> body releases glucagon, adrenaline, cortisol -> rebound hyperglycemia at dawn. Treatment: REDUCE bedtime insulin, not increase it. Distinguished from dawn phenomenon by checking 2-3 AM glucose."},

  // --- Endocrine: Thyroid (3 questions, sourced from Endocrine System.pdf pp 95-115) ---
  {unit:"U7",topic:"Thyroid - Myxedema Coma",type:"mc",q:"A 72yo woman with long-standing untreated hypothyroidism presents with hypothermia (93F), bradycardia, hypotension, stupor, and hypoglycemia after a UTI. What is the most critical initial management step?",choices:["Start levothyroxine 1.6 mcg/kg and observe at home","IV levothyroxine loading dose, hydrocortisone (until adrenal insufficiency ruled out), and supportive ICU care","Start methimazole and propranolol","High-dose aspirin for cardiovascular protection"],answer:1,explain:"Myxedema coma: most severe complication of hypothyroidism, triggered by infection/surgery/MI in an untreated patient. Features: hypothermia, hypoventilation, bradycardia, hypotension, hypoglycemia, stupor. Treatment: ABCs, warming, IV thyroxine loading dose, adjuvant hydrocortisone (until concomitant adrenal insufficiency ruled out — thyroxine can precipitate adrenal crisis if AI present), treat precipitant."},
  {unit:"U7",topic:"Thyroid - Replacement Therapy",type:"mc",q:"Why is levothyroxine (T4) preferred over liothyronine (T3) for hypothyroidism replacement?",choices:["T4 is more biologically active and works faster","T4 has a longer half-life and can be peripherally deiodinated to T3 as needed by the body","T3 is too expensive for routine use","T4 does not require renal dosing"],answer:1,explain:"T4 (thyroxine/levothyroxine) is preferred because it is less biologically active with a longer half-life, and the body can deiodinate T4 to T3 (triiodothyronine, the active form) when needed. This provides more stable levels. T3 has a short half-life and causes more fluctuation. T4 is monitored by TSH every 6-8 weeks after dose changes."},
  {unit:"U7",topic:"Thyroid - Goiter Types",type:"mc",q:"A patient has an enlarged thyroid gland, is clinically euthyroid, and has no inflammatory or neoplastic changes on workup. What is the correct terminology for this condition?",choices:["Toxic multinodular goiter","Non-toxic goiter (simple goiter)","Graves disease","Hashimoto thyroiditis"],answer:1,explain:"Non-toxic goiter = thyroid enlargement in a euthyroid individual NOT due to inflammatory or neoplastic changes. 'Simple' diffuse goiter is the early stage. Can progress to multinodular goiter over time. Toxic goiter implies hyperthyroidism. Graves disease = autoimmune hyperthyroidism with TSH receptor antibodies. Hashimoto = autoimmune hypothyroidism."},

  // --- Endocrine: Adrenal (3 questions, sourced from Endocrine System.pdf pp 115-125) ---
  {unit:"U7",topic:"Adrenal - Cushing vs Addison",type:"mc",q:"A patient on long-term prednisone 20mg daily for 3 months wants to stop abruptly. What is the most serious risk of sudden cessation?",choices:["Rebound rheumatoid arthritis flare","Secondary adrenal insufficiency due to HPA axis suppression","Acute corticosteroid psychosis","Hyperkalemic cardiac arrest"],answer:1,explain:"Prolonged exogenous corticosteroids suppress the hypothalamic-pituitary-adrenal (HPA) axis, causing secondary adrenal insufficiency. The adrenal glands atrophy and cannot produce cortisol when the exogenous steroid is withdrawn. Abrupt cessation can cause adrenal crisis: hypotension, shock, death. Taper slowly over weeks to months. Stress-dose steroids may be needed for illness or surgery."},
  {unit:"U7",topic:"Adrenal - Adrenal Crisis",type:"mc",q:"A patient with known Addison disease develops fever, vomiting, severe hypotension, and altered mental status. What is the immediate treatment?",choices:["IV normal saline and IV hydrocortisone 100mg STAT","Oral fludrocortisone and discharge with follow-up","Levothyroxine IV loading dose","Start broad-spectrum antibiotics and admit for observation"],answer:0,explain:"Adrenal crisis (Addisonian crisis): life-threatening emergency. Immediate treatment: IV fluids (normal saline — these patients are volume depleted due to aldosterone deficiency) + IV hydrocortisone 100mg STAT, then 50mg q6h or continuous infusion. Identify and treat precipitant (infection, surgery, trauma). Do not wait for confirmatory labs — treat based on clinical suspicion."},
  {unit:"U7",topic:"Adrenal - Congenital Adrenal Hyperplasia",type:"mc",q:"A newborn female has ambiguous genitalia. Labs show low cortisol, low aldosterone, and elevated androgens. What is the most likely enzyme deficiency causing congenital adrenal hyperplasia?",choices:["11-beta-hydroxylase deficiency","21-hydroxylase deficiency (autosomal recessive)","17-alpha-hydroxylase deficiency","3-beta-hydroxysteroid dehydrogenase deficiency"],answer:1,explain:"21-hydroxylase deficiency accounts for >90% of CAH cases. Autosomal recessive. Blockage at 21-hydroxylase -> decreased cortisol and aldosterone synthesis -> shunting toward androgen production. In females: ambiguous genitalia at birth, clitoral hypertrophy, hirsutism. In males: precocious puberty. Salt-wasting form includes life-threatening hyponatremia and hyperkalemia in the neonatal period."},

  // --- MSK (6 questions, sourced from Musculoskeletal System.pdf) ---
  {unit:"U3",topic:"MSK - Fracture Healing",type:"mc",q:"A patient sustains a closed radius fracture. After reduction and casting, what is the correct sequence of fracture healing stages?",choices:["Callus formation -> Hematoma -> Remodeling -> Inflammation","Hematoma -> Inflammation -> Soft callus -> Hard callus -> Remodeling","Inflammation -> Hematoma -> Remodeling -> Callus","Hard callus -> Soft callus -> Inflammation -> Remodeling"],answer:1,explain:"Fracture healing: (1) Hematoma formation (blood clot at fracture site), (2) Inflammatory phase (cytokines recruit cells), (3) Soft callus formation (fibrocartilage bridge, ~2-3 weeks), (4) Hard callus formation (endochondral ossification converts to woven bone, ~4-12 weeks), (5) Remodeling (woven bone replaced with organized lamellar bone, months to years). Weight-bearing stimulates remodeling."},
  {unit:"U3",topic:"MSK - Osteoporosis Pathophysiology",type:"mc",q:"A 65yo postmenopausal woman has osteoporosis. Which statement best describes the underlying pathophysiology?",choices:["Increased osteoblast activity with normal osteoclast function","Bone resorption by osteoclasts outpaces bone deposition by osteoblasts, with cancellous bone affected first","Cartilage degradation in weight-bearing joints with secondary bone changes","Vitamin D toxicity causing calcium leaching from bone"],answer:1,explain:"Osteoporosis: bone resorption (osteoclasts) exceeds bone deposition (osteoblasts). Cancellous (trabecular) bone is affected first due to faster turnover rate. Trabeculae become porous and thin or disappear. Postmenopausal: reduced estrogen -> increased osteoclast activity. Risk factors: age, female, low BMI, smoking, steroids, family history."},
  {unit:"U3",topic:"MSK - Osteoarthritis vs RA",type:"mc",q:"A patient has joint pain that worsens with activity and improves with rest, morning stiffness lasting 20 minutes, and Heberden nodes at the DIP joints. ESR and CRP are normal. What is the most likely diagnosis?",choices:["Rheumatoid arthritis","Osteoarthritis","Psoriatic arthritis","Gout"],answer:1,explain:"OA: mechanical pain (worse with activity, better with rest), morning stiffness <30 minutes, DIP involvement (Heberden nodes), normal inflammatory markers. RA: inflammatory pain (worse in morning, improves with activity), morning stiffness >1 hour, MCP/PIP involvement, elevated ESR/CRP, positive RF/anti-CCP. Psoriatic arthritis: DIP involvement PLUS psoriasis, nail changes, dactylitis."},
  {unit:"U3",topic:"MSK - Compartment Syndrome",type:"mc",q:"A patient with a tibial fracture in a cast reports severe, escalating pain unrelieved by opioids, and pain with passive stretch of the toes. The foot is pale and pulseless. What is the diagnosis and management?",choices:["Deep vein thrombosis — start anticoagulation","Acute compartment syndrome — immediate surgical fasciotomy","Complex regional pain syndrome — start gabapentin","Fat embolism — supportive care and oxygen"],answer:1,explain:"Compartment syndrome: increased pressure within a closed fascial compartment compromises circulation. Classic signs: pain out of proportion to injury, pain with passive stretch, paresthesia, pallor, pulselessness (late finding). Normal pulse does NOT rule out compartment syndrome. Compartment pressure >30 mmHg or within 30 mmHg of diastolic BP = fasciotomy. Delayed treatment causes irreversible muscle and nerve necrosis."},
  {unit:"U3",topic:"MSK - Septic Arthritis",type:"mc",q:"A patient presents with acute monoarticular knee swelling, erythema, warmth, fever, and severely limited range of motion. Joint aspiration shows WBC 85,000 with 90% neutrophils. What is the most critical next step?",choices:["Start oral antibiotics and follow up in 48 hours","Intra-articular corticosteroid injection","IV antibiotics and urgent orthopedic consultation for joint drainage","MRI to evaluate for osteomyelitis before treatment"],answer:2,explain:"Septic arthritis is a medical emergency. Joint fluid WBC >50,000 with >75% neutrophils strongly suggests bacterial infection. Management: IV antibiotics (vancomycin + ceftriaxone empirically until cultures) AND urgent joint drainage (serial aspiration or arthroscopic washout). Do NOT inject steroids into a septic joint. Do NOT delay antibiotics for imaging. Untreated septic arthritis destroys cartilage within 24-48 hours."},
  {unit:"U3",topic:"MSK - Osteomyelitis",type:"mc",q:"A diabetic patient has a chronic non-healing foot ulcer with exposed bone. Plain X-ray shows no abnormalities. What is the most appropriate next step to evaluate for osteomyelitis?",choices:["X-ray is sufficient to rule out osteomyelitis","MRI foot with contrast","Bone scan (technetium-99m)","Start empiric antibiotics without further imaging"],answer:1,explain:"MRI is the imaging modality of choice for osteomyelitis — detects bone marrow edema and soft tissue involvement early. Plain X-ray requires 30-50% bone mineral loss to show changes, so a normal X-ray does NOT rule out osteomyelitis (especially within first 2 weeks). Bone scan is sensitive but less specific. Probe-to-bone test: if you can probe to bone through the ulcer, osteomyelitis is likely present."},

  // --- Respiratory (4 questions, sourced from Respiratory System.pdf) ---
  {unit:"U3",topic:"Respiratory - Bronchiectasis",type:"mc",q:"A patient with cystic fibrosis develops chronic productive cough with large volumes of purulent sputum and recurrent pneumonia. CT shows permanently dilated bronchi with thickened walls. What is this condition?",choices:["Chronic bronchitis","Bronchiectasis","Pulmonary fibrosis","Tuberculosis"],answer:1,explain:"Bronchiectasis: permanent, irreversible dilation of bronchi due to destruction of muscular and elastic tissue from chronic or severe necrotizing infections. Common in cystic fibrosis, post-infectious, bronchial obstruction, HIV. CT hallmark: dilated, thick-walled airways (tram-track sign or signet-ring sign). Management: airway clearance, antibiotics for exacerbations, bronchodilators, treat underlying cause."},
  {unit:"U3",topic:"Respiratory - Cheyne-Stokes",type:"mc",q:"A patient at high altitude develops a cyclical breathing pattern of progressively deeper and faster breaths followed by apnea. What is the mechanism driving Cheyne-Stokes respiration?",choices:["Central neurogenic hyperventilation from brainstem lesion","Low O2 stimulates peripheral chemoreceptors causing hyperventilation, which blows off CO2 causing respiratory alkalosis, which depresses the respiratory center, restarting the cycle","Obstructive sleep apnea causing intermittent hypoxia","Anxiety-induced hyperventilation syndrome"],answer:1,explain:"Cheyne-Stokes at altitude: hypoxia stimulates peripheral O2 chemoreceptors -> hyperventilation -> excessive CO2 blown off -> respiratory alkalosis depresses central chemoreceptors -> apnea -> O2 falls again -> cycle repeats. Also seen in heart failure, brain injury, and at end of life. Distinguished from obstructive sleep apnea by the crescendo-decrescendo pattern and central (not obstructive) mechanism."},
  {unit:"U3",topic:"Respiratory - Pulmonary Embolism",type:"mc",q:"A 34yo woman on OCPs presents with sudden-onset pleuritic chest pain, dyspnea, and tachycardia. She has no leg swelling. D-dimer is elevated. What is the most appropriate next step?",choices:["Start therapeutic anticoagulation immediately","CT pulmonary angiography","V/Q scan","Compression ultrasound of lower extremities"],answer:1,explain:"Suspected PE in a stable patient: CT pulmonary angiography (CTPA) is the gold standard. D-dimer has high sensitivity but low specificity — elevated D-dimer does NOT diagnose PE. Start anticoagulation AFTER confirmatory imaging unless the patient is hemodynamically unstable (then empiric treatment is warranted). V/Q scan is alternative if contraindication to contrast. Wells criteria determine pre-test probability."},
  {unit:"U3",topic:"Respiratory - Scarlet Fever",type:"mc",q:"A 6yo child has fever, sore throat, and a diffuse erythematous sandpaper-like rash that started on the trunk and spread. The tongue initially had a white coating that shed, leaving a red, swollen 'strawberry' appearance. What organism and treatment?",choices:["Coxsackie virus — supportive care","Group A beta-hemolytic Streptococcus — penicillin or amoxicillin x 10 days","Staphylococcus aureus — cephalexin","Epstein-Barr virus — supportive care and avoid contact sports"],answer:1,explain:"Scarlet fever: certain strains of GABHS (Streptococcus pyogenes) infected with a bacteriophage produce an erythrogenic exotoxin. Classic triad: fever, pharyngitis, sandpaper rash. Strawberry tongue: initially white-coated, then sheds to reveal red, inflamed papillae. Treatment: same as strep pharyngitis — penicillin or amoxicillin x 10 days. Important: treat to prevent rheumatic fever (not to prevent post-streptococcal glomerulonephritis, which is not preventable with antibiotics)."}
];
