const D118_QUESTIONS = [
  // UNIT 2: Wellness & Health Promotion
  {unit:"U2",topic:"Evidence-Based Practice",type:"mc",q:"Which study design provides the highest level of evidence for clinical decision-making?",choices:["Case-control study","Cohort study","Randomized controlled trial","Cross-sectional study"],answer:2,explain:"RCTs are the gold standard — randomization controls for confounders and establishes causation."},
  {unit:"U2",topic:"Evidence-Based Practice",type:"mc",q:"A patient asks why you're using a specific treatment. You cite a systematic review of RCTs. What USPSTF grade would indicate high certainty of substantial benefit?",choices:["Grade B","Grade A","Grade C","Grade D"],answer:1,explain:"Grade A = high certainty of substantial net benefit. Grade B = high certainty of moderate benefit."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"At what age does the USPSTF recommend starting colorectal cancer screening for average-risk adults?",choices:["40 years","45 years","50 years","55 years"],answer:1,explain:"USPSTF updated recommendation in 2021: start at age 45 for average-risk adults."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"The USPSTF recommends abdominal aortic aneurysm (AAA) screening with one-time abdominal ultrasound for which group?",choices:["All adults over 65","Men 65-75 who have ever smoked","Women 65-75 who have ever smoked","Men and women 60-75 who have ever smoked"],answer:1,explain:"One-time ultrasound screening for men 65-75 who have ever smoked (at least 100 cigarettes). Not recommended for women."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"USPSTF recommends lung cancer screening with low-dose CT annually for adults aged 50-80 who have what smoking history?",choices:["10 pack-year history, current smoker","20 pack-year history, quit within 15 years OR current smoker","30 pack-year history, quit within 10 years OR current smoker","15 pack-year history, current smoker"],answer:2,explain:"USPSTF 2021: 50-80 years old, 20 pack-year history, currently smoke OR quit within past 15 years."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"Which screening is recommended by USPSTF for all adults regardless of risk factors?",choices:["Hepatitis B","Hepatitis C in adults 18-79","HIV in adults 15-65","Both B and C"],answer:3,explain:"Both Hepatitis C (18-79) and HIV (15-65) are Grade B recommendations for all adults in those age ranges."},
  {unit:"U2",topic:"Immunizations",type:"mc",q:"Which vaccines are recommended for ALL adults 19 years and older annually?",choices:["Influenza","Influenza and Tdap","Influenza and pneumococcal","Influenza and zoster"],answer:0,explain:"Influenza is the only vaccine recommended annually for ALL adults. Others have specific age/risk indications."},
  {unit:"U2",topic:"Immunizations",type:"mc",q:"At what age is the Shingrix (zoster) vaccine recommended?",choices:["50 years and older","60 years and older","65 years and older","55 years and older"],answer:0,explain:"Shingrix is recommended for adults 50 and older, given in 2 doses 2-6 months apart, even if prior Zostavax."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"USPSTF recommends depression screening for which adult population?",choices:["Adults 18+ with risk factors only","Adults 18+ with staff-assisted depression care support","All adults 18+","Adults 40+ only"],answer:2,explain:"USPSTF Grade B: Screen all adults 18+ for depression, including pregnant and postpartum women."},
  {unit:"U2",topic:"Preventive Screening",type:"mc",q:"At what interval should a Pap smear alone be done for women aged 21-65?",choices:["Every year","Every 2 years","Every 3 years","Every 5 years"],answer:2,explain:"Pap smear alone: every 3 years for women 21-65. Pap + HPV co-testing: every 5 years ages 30-65."},

  // UNIT 3: Acute Illness - EENT
  {unit:"U3",topic:"EENT",type:"mc",q:"A patient presents with unilateral eye redness, mucopurulent discharge, lid crusting, and no pain. Most likely diagnosis?",choices:["Viral conjunctivitis","Bacterial conjunctivitis","Allergic conjunctivitis","Iritis"],answer:1,explain:"Bacterial conjunctivitis: mucopurulent/purulent discharge, lid matting, typically unilateral to start. Treat with topical antibiotics."},
  {unit:"U3",topic:"EENT",type:"mc",q:"Which finding in a red eye warrants SAME-DAY ophthalmology referral?",choices:["Bilateral itching and watery discharge","Unilateral purulent discharge","Decreased visual acuity with eye pain","Seasonal exacerbation of redness"],answer:2,explain:"Decreased VA + eye pain = possible iritis, angle-closure glaucoma, or corneal ulcer — same-day referral required."},
  {unit:"U3",topic:"EENT",type:"mc",q:"A child presents with otalgia, fever, and TM with loss of landmarks, bulging, and erythema. First-line treatment?",choices:["Amoxicillin-clavulanate 90mg/kg/day","Amoxicillin 90mg/kg/day","Azithromycin","Watchful waiting for 48-72 hours in all children"],answer:1,explain:"AOM first-line: amoxicillin 90mg/kg/day (high dose) in children. Augmentin if recent antibiotics or conjunctivitis present."},
  {unit:"U3",topic:"EENT",type:"mc",q:"Treatment for allergic rhinitis — which is most effective as monotherapy?",choices:["Oral antihistamines","Intranasal antihistamines","Intranasal corticosteroids","Oral decongestants"],answer:2,explain:"Intranasal corticosteroids (fluticasone, mometasone) are the most effective single therapy for allergic rhinitis."},
  {unit:"U3",topic:"EENT",type:"mc",q:"A patient with 10 days of facial pressure, purulent nasal discharge, and maxillary toothache, not improving. Treatment?",choices:["Saline irrigation only","Amoxicillin 500mg TID x 5-7 days","Amoxicillin-clavulanate 875mg BID x 5-7 days","Azithromycin Z-pack"],answer:2,explain:"Acute bacterial rhinosinusitis: Amoxicillin-clavulanate is preferred. Amoxicillin alone if no recent antibiotics, mild, no risk factors."},

  // UNIT 3: Respiratory
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"A patient has cough, low-grade fever, wheezing after URI. CXR is normal. What is the most likely diagnosis?",choices:["Community acquired pneumonia","Acute bronchitis","Asthma exacerbation","Pertussis"],answer:1,explain:"Acute bronchitis: follows URI, cough 1-3 weeks, wheezing possible, normal CXR. Usually viral — antibiotics NOT indicated."},
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"A 65yo diabetic presents with fever, productive cough, RLL consolidation on CXR. PORT/PSI score suggests outpatient treatment. What is first-line treatment?",choices:["Azithromycin alone","Amoxicillin alone","Amoxicillin + azithromycin OR respiratory fluoroquinolone","IV ceftriaxone"],answer:2,explain:"CAP outpatient with comorbidities: combo beta-lactam + macrolide OR respiratory fluoroquinolone (levofloxacin, moxifloxacin)."},
  {unit:"U3",topic:"Respiratory - Acute",type:"mc",q:"What CURB-65 score indicates hospital admission is required for pneumonia?",choices:["Score of 1","Score of 2 or more","Score of 3 or more","Score of 4 or more"],answer:1,explain:"CURB-65: 0-1 = outpatient, 2 = consider admission, 3+ = hospitalize. Each point: Confusion, Urea>19, RR≥30, BP<90/60, age≥65."},

  // UNIT 3: GI Acute
  {unit:"U3",topic:"GI - Acute",type:"mc",q:"A patient presents with RLQ pain that began periumbilically, fever, nausea, and rebound tenderness. McBurney's point is tender. Next step?",choices:["Abdominal X-ray","CT abdomen/pelvis with contrast","Ultrasound abdomen","Start oral antibiotics and reassess"],answer:1,explain:"Appendicitis workup: CT abdomen/pelvis is gold standard in adults. Ultrasound preferred in children/pregnant women to avoid radiation."},
  {unit:"U3",topic:"GI - Acute",type:"mc",q:"Murphy's sign is positive (inspiratory arrest with RUQ palpation). Most likely diagnosis?",choices:["Appendicitis","Acute cholecystitis","Peptic ulcer disease","Pancreatitis"],answer:1,explain:"Murphy's sign = acute cholecystitis. Caused by RUQ palpation during inspiration when inflamed gallbladder descends onto examining hand."},

  // UNIT 4: Urinary/Renal
  {unit:"U4",topic:"Urinary - Acute",type:"mc",q:"An uncomplicated UTI in a non-pregnant woman. First-line treatment?",choices:["Ciprofloxacin 500mg BID x 3 days","Nitrofurantoin 100mg BID x 5 days","Trimethoprim-sulfamethoxazole DS BID x 7 days","Amoxicillin-clavulanate 875mg BID x 7 days"],answer:1,explain:"First-line for uncomplicated UTI: nitrofurantoin 5 days or TMP-SMX 3 days (if local resistance <20%). Fluoroquinolones are NOT first-line."},
  {unit:"U4",topic:"Urinary - Acute",type:"mc",q:"A woman with dysuria, flank pain, fever, CVA tenderness, nausea. Urinalysis shows WBCs, bacteria. Diagnosis and outpatient treatment?",choices:["UTI — nitrofurantoin x 5 days","Pyelonephritis — ciprofloxacin 500mg BID x 7 days","Pyelonephritis — TMP-SMX DS BID x 14 days","Pyelonephritis — amoxicillin-clavulanate x 14 days"],answer:1,explain:"Uncomplicated pyelonephritis outpatient: ciprofloxacin 500mg BID x 7 days OR TMP-SMX x 14 days if susceptible. Fluoro preferred for kidney penetration."},
  {unit:"U4",topic:"Renal",type:"mc",q:"A patient passes a kidney stone. Most common type of nephrolithiasis?",choices:["Struvite","Uric acid","Calcium oxalate","Cystine"],answer:2,explain:"80% of kidney stones are calcium oxalate. Struvite = infection stones. Uric acid = gout. Cystine = genetic disorder."},

  // UNIT 4: Dermatology
  {unit:"U4",topic:"Dermatology",type:"mc",q:"Honey-colored crusted lesions on a child's face around the nose/mouth. Most likely diagnosis and treatment?",choices:["Herpes labialis — acyclovir","Impetigo — mupirocin topical or amoxicillin-clavulanate","Contact dermatitis — topical steroids","Tinea faciei — clotrimazole"],answer:1,explain:"Impetigo: honey-crusted lesions, common in children, S. aureus or Strep. Localized: mupirocin topical. Widespread: oral antibiotics."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"A patient with well-demarcated, silvery-scaled plaques on elbows and knees. Most likely diagnosis?",choices:["Atopic dermatitis","Psoriasis","Tinea corporis","Seborrheic dermatitis"],answer:1,explain:"Psoriasis: silver-scaled plaques on extensor surfaces (elbows, knees, scalp). Nail pitting is also common."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"Dermatophyte infection of the nails (thickened, yellowed, crumbly nails). First-line oral treatment?",choices:["Fluconazole","Itraconazole","Terbinafine","Ketoconazole"],answer:2,explain:"Onychomycosis first-line oral: terbinafine (Lamisil) 250mg daily x 6 weeks (fingernails) or 12 weeks (toenails). Most effective with fewest drug interactions."},
  {unit:"U4",topic:"Dermatology",type:"mc",q:"A patient with intense nighttime itching, linear burrows between fingers, and similar symptoms in household contacts. Diagnosis and treatment?",choices:["Atopic dermatitis — triamcinolone cream","Scabies — permethrin 5% cream","Contact dermatitis — hydrocortisone","Pediculosis — permethrin 1% rinse"],answer:1,explain:"Scabies: Sarcoptes scabiei mite. Key features: nocturnal itching, burrows, household spread. Treat ALL household members with permethrin 5% from neck down."},

  // UNIT 5: Chronic Pulmonary
  {unit:"U5",topic:"Asthma",type:"mc",q:"A patient with asthma uses their rescue inhaler more than 2 days/week and wakes up with symptoms 3-4 nights/month. How is this classified?",choices:["Intermittent asthma","Mild persistent asthma","Moderate persistent asthma","Severe persistent asthma"],answer:1,explain:"Mild persistent: symptoms >2 days/week but not daily, nighttime awakenings 3-4x/month, minor limitation. Step 2 therapy: low-dose ICS."},
  {unit:"U5",topic:"Asthma",type:"mc",q:"What is the FIRST step in pharmacologic management of persistent asthma?",choices:["Add LABA","Start low-dose inhaled corticosteroid (ICS)","Start oral prednisone","Start montelukast"],answer:1,explain:"Step 2 (mild persistent): low-dose ICS is the cornerstone. LABAs are NEVER used as monotherapy in asthma — always with ICS."},
  {unit:"U5",topic:"COPD",type:"mc",q:"A 65yo smoker with FEV1/FVC <0.70 and FEV1 55% predicted. Which GOLD classification?",choices:["GOLD 1 — Mild","GOLD 2 — Moderate","GOLD 3 — Severe","GOLD 4 — Very severe"],answer:1,explain:"GOLD 2 (Moderate): FEV1 50-79% predicted. GOLD 1: ≥80%. GOLD 3: 30-49%. GOLD 4: <30%."},
  {unit:"U5",topic:"COPD",type:"mc",q:"Most important intervention shown to slow COPD progression?",choices:["Long-acting bronchodilators","Inhaled corticosteroids","Smoking cessation","Pulmonary rehabilitation"],answer:2,explain:"Smoking cessation is the ONLY intervention proven to slow decline in FEV1 and alter COPD progression. Everything else manages symptoms."},
  {unit:"U5",topic:"Pulmonary Embolism",type:"mc",q:"A patient with sudden dyspnea, pleuritic chest pain, tachycardia, and recent long flight. What is the FIRST diagnostic test?",choices:["V/Q scan","CT pulmonary angiography (CTPA)","D-dimer if low pretest probability","Chest X-ray"],answer:2,explain:"Use Wells criteria first. If low pretest probability → D-dimer. If elevated → CTPA. CTPA is gold standard but D-dimer can rule out in low-probability patients."},

  // UNIT 5: Chronic Cardiovascular
  {unit:"U5",topic:"Hypertension",type:"mc",q:"A 55yo with BP 145/92 on two separate visits. No other comorbidities. ACC/AHA stage?",choices:["Elevated BP","Stage 1 HTN","Stage 2 HTN","Hypertensive urgency"],answer:1,explain:"ACC/AHA 2017: Stage 1 HTN = 130-139/80-89. Stage 2 = ≥140/90. First-line lifestyle changes ± medication based on CVD risk."},
  {unit:"U5",topic:"Hypertension",type:"mc",q:"A diabetic patient with HTN and CKD. What is the preferred antihypertensive class?",choices:["Calcium channel blockers","Beta-blockers","ACE inhibitor or ARB","Thiazide diuretics"],answer:2,explain:"ACE inhibitors or ARBs are preferred in diabetics with HTN and CKD due to nephroprotective effects (reduce proteinuria, slow GFR decline)."},
  {unit:"U5",topic:"Heart Failure",type:"mc",q:"A patient with dyspnea on exertion, orthopnea, and bilateral crackles. Echo shows EF of 35%. What is the diagnosis?",choices:["HFpEF","HFrEF","Diastolic dysfunction only","Cor pulmonale"],answer:1,explain:"HFrEF (Heart Failure with reduced EF): EF <40%. HFpEF: EF ≥50%. Treatment differs significantly — ACE/ARB + beta-blocker + aldosterone antagonist for HFrEF."},
  {unit:"U5",topic:"Heart Failure",type:"mc",q:"NYHA Class III heart failure is defined as?",choices:["No symptoms","Symptoms with moderate exertion, slight limitation","Symptoms with less than ordinary activity, marked limitation","Symptoms at rest"],answer:2,explain:"NYHA Class III: marked limitation — comfortable only at rest, symptoms with less than ordinary activity. Class II = slight limitation. Class IV = symptoms at rest."},
  {unit:"U5",topic:"CAD",type:"mc",q:"A patient with stable angina has CCS Class II. What does this mean?",choices:["No angina","Angina with ordinary activity, slight limitation","Angina with less than ordinary activity, marked limitation","Angina at rest"],answer:1,explain:"CCS Class II: slight limitation — angina with ordinary exertion (walking >2 blocks, climbing >1 flight). Class I = no ordinary activity limitation."},

  // UNIT 5: Chronic GI
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"Most common cause of peptic ulcer disease?",choices:["NSAID use","H. pylori infection","Stress","Alcohol use"],answer:1,explain:"H. pylori causes ~70% of duodenal ulcers and ~50% of gastric ulcers. NSAIDs are second most common. Test and treat H. pylori first."},
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"First-line treatment for H. pylori eradication?",choices:["Omeprazole + amoxicillin","Clarithromycin triple therapy (PPI + clarithromycin + amoxicillin)","Quadruple therapy (PPI + bismuth + metronidazole + tetracycline)","PPI monotherapy"],answer:2,explain:"Clarithromycin triple therapy 14 days if local clarithromycin resistance <15%. Quadruple therapy preferred in high-resistance areas or prior macrolide exposure."},
  {unit:"U5",topic:"GI - Chronic",type:"mc",q:"IBS diagnostic criteria (Rome IV): recurrent abdominal pain at least how often, associated with defecation or stool changes?",choices:["Once a month for 3 months","Once a week for 3 months","Daily for 1 month","Twice a week for 6 months"],answer:1,explain:"Rome IV IBS criteria: recurrent abdominal pain ≥1 day/week for 3 months, associated with 2+ of: related to defecation, change in stool frequency, change in stool form."},

  // UNIT 6: Chronic MSK & Rheumatic
  {unit:"U6",topic:"MSK - Chronic",type:"mc",q:"A patient with first MTP joint swelling, severe acute pain, and serum uric acid of 9.2. Synovial fluid shows negatively birefringent needle-shaped crystals. Diagnosis?",choices:["Pseudogout","Septic arthritis","Gout","Rheumatoid arthritis"],answer:2,explain:"Gout: negatively birefringent needle-shaped monosodium urate crystals. Pseudogout: positively birefringent rhomboid calcium pyrophosphate crystals."},
  {unit:"U6",topic:"MSK - Chronic",type:"mc",q:"First-line treatment for acute gout flare?",choices:["Allopurinol","Colchicine or NSAIDs","Prednisone only","Febuxostat"],answer:1,explain:"Acute gout: NSAIDs (indomethacin), colchicine, or steroids. Allopurinol and febuxostat are for PREVENTION — do NOT start during an acute attack."},
  {unit:"U6",topic:"Rheumatic",type:"mc",q:"A woman with malar rash, photosensitivity, oral ulcers, positive ANA and anti-dsDNA antibodies, thrombocytopenia. Diagnosis?",choices:["Rheumatoid arthritis","Dermatomyositis","Systemic lupus erythematosus","Sjogren syndrome"],answer:2,explain:"SLE: malar rash, photosensitivity, oral ulcers, serositis, renal, neuro, hematologic, immunologic (ANA, anti-dsDNA, anti-Sm). 4/11 criteria needed."},
  {unit:"U6",topic:"Rheumatic",type:"mc",q:"A 70yo woman with bilateral shoulder/hip girdle pain, stiffness worse in the morning, ESR >50. What diagnosis to consider first?",choices:["Fibromyalgia","Polymyalgia rheumatica","RA","Giant cell arteritis"],answer:1,explain:"PMR: older adults, bilateral proximal muscle pain/stiffness, elevated ESR/CRP, dramatic response to low-dose prednisone. Always rule out giant cell arteritis (temporal arteritis)."},

  // UNIT 6: Chronic Neurologic
  {unit:"U6",topic:"Neurology",type:"mc",q:"Classic triad of Parkinson's disease?",choices:["Tremor, rigidity, postural instability","Tremor, chorea, dementia","Rigidity, spasticity, clonus","Bradykinesia, tremor, rigidity"],answer:3,explain:"Parkinson's triad: resting tremor (pill-rolling), rigidity (cogwheel), bradykinesia. Plus postural instability. Dopaminergic neuron loss in substantia nigra."},
  {unit:"U6",topic:"Neurology",type:"mc",q:"A 40yo woman with relapsing-remitting neurologic symptoms, optic neuritis, Lhermitte's sign, and MRI white matter plaques. Diagnosis?",choices:["ALS","Guillain-Barre syndrome","Multiple sclerosis","Myasthenia gravis"],answer:2,explain:"MS: demyelinating disease, young adults (F>M), relapsing-remitting, optic neuritis, Lhermitte's sign, periventricular white matter lesions on MRI."},
  {unit:"U6",topic:"Neurology",type:"mc",q:"Migraine with aura vs without aura — what characterizes aura?",choices:["Nausea and vomiting","Phonophobia","Fully reversible neurologic symptoms lasting 5-60 min","Unilateral throbbing pain"],answer:2,explain:"Migraine aura: fully reversible neurologic symptoms (visual, sensory, speech) developing over ≥5 min, lasting 5-60 min, followed by headache within 60 min."},

  // UNIT 7: Endocrine/Metabolic
  {unit:"U7",topic:"Diabetes",type:"mc",q:"Diagnostic criteria for Type 2 Diabetes Mellitus (any ONE of these). Which is correct?",choices:["Fasting glucose ≥110 mg/dL","HbA1c ≥6.5%","2-hour glucose ≥180 mg/dL on OGTT","Random glucose ≥180 with symptoms"],answer:1,explain:"DM diagnosis: FBG ≥126, HbA1c ≥6.5%, 2hr OGTT ≥200, OR random glucose ≥200 with symptoms. Prediabetes: FBG 100-125, HbA1c 5.7-6.4%."},
  {unit:"U7",topic:"Diabetes",type:"mc",q:"First-line medication for Type 2 DM with no contraindications?",choices:["Insulin","GLP-1 agonist","Metformin","SGLT-2 inhibitor"],answer:2,explain:"Metformin is first-line for T2DM unless contraindicated (eGFR <30, contrast dye, etc.). Add-ons depend on comorbidities — GLP-1 or SGLT-2 if CVD/HF/CKD."},
  {unit:"U7",topic:"Thyroid",type:"mc",q:"A patient with fatigue, cold intolerance, weight gain, constipation, bradycardia, and dry skin. TSH is elevated, free T4 is low. Diagnosis and treatment?",choices:["Hyperthyroidism — methimazole","Hypothyroidism — levothyroxine","Subclinical hypothyroidism — monitor only","Hashimoto's thyroiditis — selenium"],answer:1,explain:"Primary hypothyroidism: high TSH, low free T4. Most common cause = Hashimoto's (autoimmune). Treatment: levothyroxine, adjust dose to normalize TSH."},
  {unit:"U7",topic:"Thyroid",type:"mc",q:"A patient with heat intolerance, weight loss, tremor, palpitations, diarrhea, exophthalmos, and diffuse goiter. TSH is suppressed. Diagnosis?",choices:["Toxic multinodular goiter","Graves' disease","Thyroid storm","De Quervain thyroiditis"],answer:1,explain:"Graves' disease: most common hyperthyroidism, autoimmune (TSH receptor antibodies), exophthalmos (pathognomonic), diffuse goiter, pretibial myxedema."},

  // UNIT 7: Mental Health
  {unit:"U7",topic:"Mental Health",type:"mc",q:"A patient meets criteria for Major Depressive Disorder. First-line pharmacotherapy?",choices:["Bupropion","Tricyclic antidepressant (TCA)","SSRI","Benzodiazepine"],answer:2,explain:"SSRIs are first-line for MDD due to efficacy and tolerability profile. SNRIs are also acceptable. TCAs and MAOIs are second/third line due to side effect profiles."},
  {unit:"U7",topic:"Mental Health",type:"mc",q:"DSM-5 criteria for MDD requires how many symptoms for at least how many weeks?",choices:["3 symptoms for 1 week","5 symptoms for 2 weeks","4 symptoms for 2 weeks","5 symptoms for 1 month"],answer:1,explain:"MDD: 5+ symptoms for ≥2 weeks, including depressed mood OR anhedonia. Symptoms: sleep, interest, guilt, energy, concentration, appetite, psychomotor, suicidality."},
  {unit:"U7",topic:"Mental Health",type:"mc",q:"A patient on an SSRI for 4 weeks reports little improvement. What is the appropriate next step?",choices:["Switch to a TCA immediately","Increase dose if at submaximal dosing or switch after adequate trial (6-8 weeks)","Add a benzodiazepine","Add lithium augmentation"],answer:1,explain:"Adequate antidepressant trial = 6-8 weeks at therapeutic dose. At 4 weeks with no response: ensure therapeutic dosing. Full trial before switching."},

  // CASE SCENARIOS
  {unit:"U5",topic:"Cardiovascular - Case",type:"case",q:"A 58yo male smoker with DM and HTN presents with 20 min of substernal chest pressure radiating to left arm, diaphoresis, and nausea. BP 155/95, HR 100. EKG shows ST elevation in leads II, III, aVF. What is the most likely diagnosis and immediate management priority?",choices:["NSTEMI — start heparin and schedule cath within 24-72 hrs","Inferior STEMI — activate cath lab, aspirin 325mg, heparin, call EMS transfer","Stable angina — nitroglycerine and discharge with stress test","Unstable angina — admit for monitoring"],answer:1,explain:"ST elevation in II, III, aVF = inferior STEMI (RCA). Time is muscle — activate cath lab immediately. Aspirin 325mg chewed, heparin, O2 if hypoxic, nitroglycerin (CAUTION in inferior MI — may cause hypotension if RV involved)."},
  {unit:"U3",topic:"Respiratory - Case",type:"case",q:"A 72yo nursing home patient with fever 102, HR 110, RR 24, BP 105/70, O2 sat 88% on room air, and left lower lobe infiltrate on CXR. CURB-65 score = 4. Best next step?",choices:["Discharge with oral levofloxacin","Admit to general floor with IV antibiotics","ICU admission given score and hemodynamics","Start azithromycin and recheck in 48 hours"],answer:2,explain:"CURB-65 of 4 + hemodynamic instability (hypotension, tachycardia) + O2 sat 88% = severe CAP requiring ICU-level care. IV broad-spectrum antibiotics, respiratory support."},
  {unit:"U7",topic:"Diabetes - Case",type:"case",q:"A 52yo with T2DM, HTN, and established ASCVD (prior MI) presents for medication management. HbA1c is 8.2%. They are on metformin. What medication should be added given their cardiovascular history?",choices:["Add sulfonylurea (glipizide)","Add GLP-1 agonist (semaglutide or liraglutide) with proven CV benefit","Add DPP-4 inhibitor (sitagliptin)","Add insulin glargine"],answer:1,explain:"ADA guidelines: T2DM + established ASCVD → add GLP-1 RA (semaglutide, liraglutide) OR SGLT-2 inhibitor with proven CV benefit regardless of HbA1c. Reduces MACE."}
];
