const D120_QUESTIONS = [
  // UNIT 2: Women's Health
  {unit:"U2",topic:"Women's Health",type:"mc",q:"Four principles of practice in women's health primary care?",choices:["Autonomy, Beneficence, Non-maleficence, Justice","Prevention, Screening, Treatment, Referral","Holism, Advocacy, Collaboration, Evidence-based care","Safety, Efficacy, Equity, Access"],answer:0,explain:"The 4 bioethical principles: Autonomy (patient's right to decide), Beneficence (do good), Non-maleficence (do no harm), Justice (fair distribution of care). Core to all women's health practice."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"Classic presentation of bacterial vaginosis (BV)?",choices:["Thick white cottage-cheese discharge, pruritus, pH <4.5","Thin gray/white homogeneous discharge, fishy odor, pH >4.5, positive whiff test","Frothy yellow-green discharge, pruritus, strawberry cervix","Mucopurulent cervicitis, no vaginal discharge"],answer:1,explain:"BV: Gardnerella vaginalis, thin gray discharge, fishy amine odor (whiff test positive), pH >4.5, clue cells on wet mount. Amsel criteria: 3 of 4. Treat: metronidazole 500mg BID x 7 days."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"Trichomonas vaginitis — characteristic findings and treatment?",choices:["Clue cells, treat with fluconazole","Frothy green discharge, strawberry cervix, treat with metronidazole for BOTH partners","Thick white discharge, treat with topical clotrimazole","Thin discharge, treat with clindamycin"],answer:1,explain:"Trich (Trichomonas vaginalis): STI — frothy, malodorous, yellow-green discharge, strawberry cervix (punctate hemorrhages), pH >4.5. Treat BOTH partners with metronidazole 2g single dose."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"Vulvovaginal candidiasis — diagnosis and treatment?",choices:["pH >4.5, treat metronidazole","Clue cells on wet prep, treat clindamycin","pH <4.5, budding hyphae/pseudohyphae on wet prep with 10% KOH, treat fluconazole 150mg x1","STI — treat both partners"],answer:2,explain:"VVC (Candida): thick white cottage-cheese discharge, pruritus, burning, pH <4.5, hyphae on KOH prep. Uncomplicated: fluconazole 150mg PO x1 OR topical azoles. Complicated: fluconazole x3 doses."},
  {unit:"U2",topic:"Women's Health - Breast",type:"mc",q:"USPSTF recommendation for breast cancer screening in average-risk women?",choices:["Annual mammogram starting age 40","Mammogram every 2 years starting age 40","Mammogram every 2 years ages 50-74, shared decision-making 40-49","Annual mammogram starting age 50"],answer:2,explain:"USPSTF 2024 updated: Biennial mammogram recommended for all women starting at age 40 (updated from 50). Shared decision-making for individual risk."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"Which STI presents with painful genital ulcers with a soft base (soft chancre)?",choices:["Syphilis (primary)","Herpes simplex","Chancroid (Haemophilus ducreyi)","Lymphogranuloma venereum"],answer:2,explain:"Chancroid: painful soft ulcer + tender inguinal lymphadenopathy (bubo). Caused by H. ducreyi. Syphilis = painless hard chancre. HSV = painful vesicles/ulcers."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"Primary syphilis presentation and treatment?",choices:["Painless indurated ulcer (chancre), treat with penicillin G benzathine 2.4M units IM x1","Painful ulcer, treat with azithromycin","Diffuse rash and condyloma lata, treat with doxycycline","Gummas, treat with IV penicillin"],answer:0,explain:"Primary syphilis: painless, indurated chancre at entry site, heals spontaneously in 3-6 weeks. Treatment: penicillin G benzathine 2.4M units IM single dose. Secondary: rash on palms/soles, condyloma lata. Tertiary: gummas, cardiovascular, neuro."},
  {unit:"U2",topic:"Women's Health - Gynecology",type:"mc",q:"PID (pelvic inflammatory disease) — what is the minimum diagnostic criteria?",choices:["Fever + elevated WBC + cervical motion tenderness","Cervical motion tenderness (CMT) OR uterine tenderness OR adnexal tenderness","Positive gonorrhea culture","Positive pregnancy test ruled out + abdominal pain"],answer:1,explain:"PID minimum criteria (CDC): cervical motion tenderness (CMT), uterine tenderness, OR adnexal tenderness in sexually active female with pelvic pain and no other etiology. Treat empirically."},

  // UNIT 3: Pregnant Patient
  {unit:"U3",topic:"Obstetrics - Antepartum",type:"mc",q:"Naegele's rule for calculating estimated due date (EDD)?",choices:["Last menstrual period + 9 months","First day of LMP + 280 days (or +7 days -3 months +1 year)","Date of conception + 266 days","LMP + 10 months"],answer:1,explain:"Naegele's rule: First day of LMP + 7 days, then subtract 3 months, add 1 year (= +280 days). Example: LMP Jan 1 → EDD Oct 8."},
  {unit:"U3",topic:"Obstetrics - Antepartum",type:"mc",q:"Preeclampsia is defined as?",choices:["HTN >150/100 before 20 weeks gestation","New onset HTN ≥140/90 after 20 weeks + proteinuria OR end-organ damage","Chronic HTN + proteinuria at any gestation","Gestational HTN + headache after 37 weeks"],answer:1,explain:"Preeclampsia: new HTN ≥140/90 after 20 weeks + proteinuria (≥300mg/24hr or protein:creatinine ≥0.3) OR severe features (platelets <100K, Cr >1.1, LFTs 2x normal, pulmonary edema, headache, visual disturbances)."},
  {unit:"U3",topic:"Obstetrics - Antepartum",type:"mc",q:"Gestational diabetes — universal screening at what weeks?",choices:["10-14 weeks","16-20 weeks","24-28 weeks","32-36 weeks"],answer:2,explain:"GDM screening: 1-hour 50g glucose challenge test (GCT) at 24-28 weeks for all pregnant women. If ≥140 mg/dL → 3-hour 100g OGTT for diagnosis."},
  {unit:"U3",topic:"Obstetrics - Antepartum",type:"mc",q:"A pregnant woman at 28 weeks has BP 155/102, severe headache, visual disturbances, and RUQ pain. Labs: platelets 90K, AST 3x normal. What is this?",choices:["Preeclampsia without severe features","HELLP syndrome","Gestational HTN","Chronic hypertension"],answer:1,explain:"HELLP syndrome: Hemolysis, Elevated Liver enzymes, Low Platelets. Severe feature of preeclampsia. Requires delivery regardless of gestational age. IV magnesium for seizure prophylaxis."},
  {unit:"U3",topic:"Obstetrics - Antepartum",type:"mc",q:"What is the recommended daily folic acid supplementation for women of childbearing age to prevent neural tube defects?",choices:["0.4mg (400mcg) daily","1mg daily","4mg daily","2mg daily"],answer:0,explain:"USPSTF: 0.4-0.8mg (400-800mcg) folic acid daily for all women planning/capable of pregnancy, starting 1 month before conception. High-risk (prior NTD): 4mg daily."},
  {unit:"U3",topic:"Obstetrics - Complications",type:"mc",q:"Placenta previa vs abruptio placenta — key differentiating feature?",choices:["Both present with painful bleeding","Placenta previa = painless bleeding; Abruptio = painful bleeding","Placenta previa = painful; Abruptio = painless","Both are painless"],answer:1,explain:"Placenta previa: painless bright red bleeding (placenta covering cervical os). Abruptio placentae: painful dark bleeding, uterine tenderness/rigidity, maternal-fetal compromise. NO digital exam with previa."},

  // UNIT 4: Men's Health
  {unit:"U4",topic:"Men's Health",type:"mc",q:"Current USPSTF recommendation for PSA-based prostate cancer screening?",choices:["Screen all men starting at age 50","Screen all men age 55-69 with shared decision-making","Recommend against screening for all men","Screen high-risk men (Black, family history) starting at 40"],answer:1,explain:"USPSTF Grade C: PSA screening in men ages 55-69 — shared decision-making (individual discussion of benefits/harms). Men <55 or ≥70 — recommend against routine screening."},
  {unit:"U4",topic:"Men's Health",type:"mc",q:"BPH symptoms are assessed using what validated tool?",choices:["PHQ-9","AUA Symptom Score (IPSS)","CAGE questionnaire","HAM-A"],answer:1,explain:"BPH: International Prostate Symptom Score (IPSS)/AUA Symptom Score — 7 questions about urinary symptoms. Mild 0-7, Moderate 8-19, Severe 20-35. Guides treatment decisions."},
  {unit:"U4",topic:"Men's Health",type:"mc",q:"First-line medication for BPH symptoms?",choices:["5-alpha reductase inhibitor (finasteride)","Alpha-blocker (tamsulosin, terazosin)","PDE-5 inhibitor (tadalafil)","Anticholinergics"],answer:1,explain:"BPH first-line: alpha-blockers (tamsulosin, alfuzosin) — relax smooth muscle, fast symptom relief. 5-ARIs (finasteride) shrink prostate — used for large glands or combination therapy. Tadalafil approved for BPH."},
  {unit:"U4",topic:"Men's Health",type:"mc",q:"Testicular torsion — time window for surgical salvage?",choices:["Within 6 hours = 100% salvage; after 24 hours = near 0%","Within 2 hours","Within 12 hours","Within 48 hours"],answer:0,explain:"Testicular torsion: UROLOGIC EMERGENCY. <6 hours = ~100% salvage. 6-12 hours = ~50%. >24 hours = ~10%. NEVER delay for imaging if clinical suspicion high — emergency scrotal exploration."},

  // UNIT 5: LGBTQIAP+
  {unit:"U5",topic:"LGBTQIAP+",type:"mc",q:"PrEP (pre-exposure prophylaxis) for HIV prevention — current first-line regimen?",choices:["Tenofovir/emtricitabine (Truvada or Descovy) daily","Single-dose zidovudine post-exposure","Monthly injectable cabotegravir only","Doxycycline daily"],answer:0,explain:"PrEP first-line: tenofovir disoproxil/emtricitabine (Truvada) OR tenofovir alafenamide/emtricitabine (Descovy) daily oral. Injectable cabotegravir (Apretude) every 2 months is alternative. >99% effective when taken consistently."},
  {unit:"U5",topic:"LGBTQIAP+",type:"mc",q:"CDC HIV screening recommendation for adults?",choices:["Test only high-risk individuals","One-time screening for all adults 15-65","Annual screening for sexually active adults, more frequently for high-risk","Test only when symptoms present"],answer:1,explain:"USPSTF: HIV screening for ALL adults 15-65 (Grade A). High-risk individuals (MSM, IVDU, multiple partners) should be screened at least annually. Pregnant women screened at first prenatal visit."},
  {unit:"U5",topic:"LGBTQIAP+",type:"mc",q:"For transgender women (MTF) on feminizing hormone therapy, what health screening is most important to discuss?",choices:["Prostate cancer screening per age guidelines","Cervical cancer screening (even without cervix)","Cardiovascular risk from estrogen therapy + VTE risk","Testosterone level monitoring only"],answer:2,explain:"MTF on estrogen: increased VTE risk, cardiovascular risk, prolactinoma risk. Prostate cancer screening still applies (prostate still present). No cervical cancer screen if cervix removed."},

  // UNIT 6: Older Adult
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"The Timed Up and Go (TUG) test is used to assess what in older adults?",choices:["Cognitive function","Fall risk and mobility","Depression screening","Nutritional status"],answer:1,explain:"TUG test: patient rises from chair, walks 10 feet, turns, returns, sits. >12 seconds = increased fall risk. Simple, validated fall risk screen for older adults."},
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"Three screening questions for falls in older adults (per geriatric guidelines)?",choices:["Any falls in past year? Fear of falling? Difficulty walking?","Pain level, medication count, vision problems?","Weight loss, continence issues, sleep quality?","Depression screen, cognitive screen, sensory screen?"],answer:0,explain:"Three fall screening questions: (1) Have you fallen in the past year? (2) Do you feel unsteady when standing/walking? (3) Are you worried about falling? Yes to any = full fall risk assessment."},
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"What is the Beers Criteria used for?",choices:["Assessing fall risk in elderly","Identifying potentially inappropriate medications for older adults (≥65)","Grading dementia severity","Predicting 30-day mortality"],answer:1,explain:"Beers Criteria (AGS): list of potentially inappropriate medications in adults ≥65 — those with increased adverse effects outweighing benefits. Examples: anticholinergics, benzodiazepines, certain NSAIDs, first-gen antihistamines."},
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"Delirium vs Dementia — key differentiating feature?",choices:["Delirium is gradual onset; dementia is acute","Delirium has acute onset with fluctuating course; dementia has gradual onset","Both have fluctuating consciousness","Dementia is reversible; delirium is not"],answer:1,explain:"Delirium: ACUTE onset, fluctuating course, impaired attention, often reversible with treatment of underlying cause. Dementia: gradual/insidious onset, progressive, stable consciousness (until late stages)."},
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"What is the POLST (MOLST) form used for?",choices:["Advance directive for young healthy adults","Medical orders for life-sustaining treatment for seriously ill patients","Standard DNR for all patients","Consent form for surgery"],answer:1,explain:"POLST (Physician Orders for Life-Sustaining Treatment): medical orders for patients with serious illness/advanced age — documents specific decisions about CPR, mechanical ventilation, hospitalization, artificial nutrition. More actionable than advance directive."},
  {unit:"U6",topic:"Geriatrics",type:"mc",q:"Difference between palliative care and hospice?",choices:["They are the same thing","Palliative care = at any stage of illness alongside curative treatment; Hospice = life expectancy ≤6 months, comfort-focused, no curative treatment","Hospice can continue curative treatment","Palliative care is only for cancer"],answer:1,explain:"Palliative care: symptom management at ANY disease stage, alongside curative therapy. Hospice: subset of palliative care for terminal patients (prognosis ≤6 months), comfort-only, curative therapy stopped."},

  // UNIT 7: Special Populations
  {unit:"U7",topic:"IPV",type:"mc",q:"Which screening tool is recommended by the CDC for intimate partner violence (IPV) screening?",choices:["CAGE questionnaire","RADAR or HITS","PHQ-9","AUDIT-C"],answer:1,explain:"CDC-recommended IPV tools: RADAR (Remember to ask, Ask directly, Document, Assess safety, Review options) or HITS (Hurt, Insult, Threaten, Scream). Universal screening recommended for reproductive-age women."},
  {unit:"U7",topic:"Pain Management",type:"mc",q:"CDC recommendation for initial opioid prescribing for chronic pain?",choices:["Start high dose and titrate down","Prescribe lowest effective dose, reassess frequently, use non-opioid therapies first","Prescribe ER/LA opioids for all chronic pain","No limits on initial prescribing"],answer:1,explain:"CDC 2022 guideline: use non-opioid therapies first, prescribe lowest effective dose, immediate-release preferred over extended-release initially, reassess risk-benefit frequently. Calculate MME (morphine milligram equivalents)."},
  {unit:"U7",topic:"Substance Abuse",type:"mc",q:"First-line medication for opioid use disorder (OUD)?",choices:["Naltrexone only","Methadone only","Buprenorphine/naloxone (Suboxone) — preferred outpatient","Clonidine for withdrawal"],answer:2,explain:"MOUD (Medications for Opioid Use Disorder): buprenorphine/naloxone (Suboxone) — first-line outpatient, reduces cravings and withdrawal. Methadone — OTP clinic only. Naltrexone (Vivitrol) — after detox, monthly injection."},
  {unit:"U7",topic:"Travel Health",type:"mc",q:"Where should you check for current travel health advisories and vaccination recommendations?",choices:["WHO website","CDC Travelers' Health website (cdc.gov/travel)","Local health department only","State Department website"],answer:1,explain:"CDC Travelers' Health (cdc.gov/travel): destination-specific vaccine requirements, disease risks, prophylaxis recommendations. Check before every international travel counseling visit."},
  {unit:"U7",topic:"Travel Health",type:"mc",q:"Malaria prophylaxis for travel to chloroquine-resistant areas — preferred agent?",choices:["Chloroquine","Atovaquone-proguanil (Malarone) or doxycycline or mefloquine","Primaquine only","Amoxicillin"],answer:1,explain:"Chloroquine-resistant malaria: atovaquone-proguanil (Malarone), doxycycline, or mefloquine. Malarone well-tolerated, start 1-2 days before, during, and 7 days after travel."},

  // UNIT 8: Care Coordination
  {unit:"U8",topic:"Scope of Practice",type:"mc",q:"The APRN Consensus Model defines NP practice as?",choices:["Dependent on physician supervision in all states","Full practice authority in all states","Standardized licensure, accreditation, certification, education (LACE) framework — practice authority varies by state","Only hospital-based practice"],answer:2,explain:"APRN Consensus Model (LACE): Licensure, Accreditation, Certification, Education — provides framework for standardized NP practice. Practice authority varies: Full practice (independent), Reduced, Restricted by state."},
  {unit:"U8",topic:"Care Coordination",type:"mc",q:"Patient-Centered Medical Home (PCMH) is characterized by?",choices:["Specialist-led fragmented care","Comprehensive, coordinated, accessible care with a personal physician leading a team","Emergency department as primary access point","Insurance-driven care decisions only"],answer:1,explain:"PCMH: personal physician leading a team, whole-person orientation, coordinated integrated care, enhanced access, quality/safety focus. Reduces ED visits, hospitalizations, improves chronic disease management."},

  // Case Scenarios
  {unit:"U3",topic:"Obstetrics - Case",type:"case",q:"A 32yo G2P1 at 36 weeks presents with sudden onset painless bright red vaginal bleeding. No contractions. BP 118/72. Fetal heart tones are reassuring. What is the priority action and what should you AVOID?",choices:["Digital cervical exam to check dilation — then decide","No digital exam — ultrasound to confirm placenta location, NPO, IV access, type & crossmatch, emergency OB consult","Start Pitocin and prepare for delivery","Discharge home with pelvic rest instructions"],answer:1,explain:"Painless antepartum bleeding at 36 wks = placenta previa until proven otherwise. NO digital exam (can cause massive hemorrhage). Bedside ultrasound first. IV access, type & screen, NPO, emergency OB."},
  {unit:"U7",topic:"Geriatrics - Case",type:"case",q:"An 82yo with dementia is brought in for confusion and agitation. Her daughter notes this started 2 days ago — she was 'back to normal' last week. Vitals: T 101.2, HR 95, O2 sat 93%. What is the most likely diagnosis and first priority?",choices:["Worsening dementia — adjust antipsychotic","Delirium — find and treat underlying cause (sepsis, UTI, pneumonia likely given fever and low O2)","Stroke — immediate CT head","Psychiatric emergency — psychiatric hold"],answer:1,explain:"ACUTE change in cognition over days in a patient with dementia baseline = delirium (not dementia worsening). Fever + low O2 sat = likely infectious trigger (UTI, pneumonia). Treat the cause. Avoid antipsychotics unless safety risk."},
  {unit:"U5",topic:"LGBTQIAP+ - Case",type:"case",q:"A 28yo MSM presents requesting PrEP. He has had unprotected receptive anal sex with 3 partners in the past 6 months. He is HIV negative today. What labs do you need BEFORE starting PrEP?",choices:["HIV test only","HIV test, renal function (Cr/eGFR), HBV status, STI screening (gonorrhea, chlamydia, syphilis), HCV","HIV and CBC only","No labs needed — start PrEP immediately"],answer:1,explain:"Before PrEP: HIV test (must be negative), renal function (tenofovir is nephrotoxic — check eGFR), HBV status (FTC active against HBV — stopping can cause flare), STI panel. Monitor every 3 months while on PrEP."},

  // --- D120 expansion: Special Populations (10 questions) ---
  {unit:"U7",topic:"Geriatrics - Falls",type:"mc",q:"An 82yo woman has fallen twice in the past 3 months. She lives alone. What is the most important multifactorial intervention to prevent future falls?",choices:["Tell her to be more careful","Vitamin D supplementation alone","Medication review, home safety assessment, PT for gait/balance training, vision check, and vitamin D","Immediate nursing home placement"],answer:2,explain:"Fall prevention requires multifactorial assessment: medication review (especially benzodiazepines, anticholinergics, antihypertensives), home hazard modification, physical therapy (strength and balance training), vision assessment, vitamin D 800-1000 IU daily. Single interventions are less effective than bundled approaches."},
  {unit:"U7",topic:"Geriatrics - Delirium vs Dementia",type:"mc",q:"What is the key differentiating feature between delirium and dementia?",choices:["Dementia has an acute onset; delirium is gradual","Delirium has acute onset with fluctuating course and inattention; dementia is chronic and progressive","They are the same condition","Delirium only occurs in the ICU"],answer:1,explain:"Delirium: acute onset (hours-days), fluctuating course, inattention, altered consciousness, often reversible (treat underlying cause). Dementia: insidious onset (months-years), progressive, attention relatively preserved early, usually irreversible. A patient with dementia CAN develop delirium (delirium superimposed on dementia) — this is common and often missed."},
  {unit:"U7",topic:"Geriatrics - Polypharmacy",type:"mc",q:"A 78yo takes 12 medications including diphenhydramine for sleep, oxybutynin for urgency, and glyburide for diabetes. Which medication is MOST concerning per Beer's Criteria?",choices:["Metformin","Diphenhydramine — strongly anticholinergic, avoid in older adults","Lisinopril","Atorvastatin"],answer:1,explain:"Beer's Criteria: diphenhydramine is strongly anticholinergic and should be avoided in older adults (confusion, constipation, urinary retention, falls). Oxybutynin is also anticholinergic. Glyburide: long half-life sulfonylurea — causes prolonged hypoglycemia, also on Beer's list. Review all anticholinergics and consider deprescribing."},
  {unit:"U4",topic:"Pediatrics - Growth",type:"mc",q:"A 4-month-old exclusively breastfed infant has dropped from the 50th to the 5th percentile for weight over 6 weeks. Length and head circumference remain at the 50th percentile. What is the most likely diagnosis?",choices:["Constitutional growth delay","Failure to thrive (inadequate caloric intake)","Endocrine disorder","Genetic syndrome"],answer:1,explain:"Weight dropping across percentiles with preserved length and head circumference = inadequate caloric intake (most common cause of FTT). Breastfeeding assessment: latch, milk supply, frequency/duration of feeds. Supplement with formula or pumped milk after breastfeeding. Refer lactation consultant. Endocrine causes usually affect height first. Genetic syndromes affect all parameters (weight, length, head circumference proportionally)."},
  {unit:"U4",topic:"Pediatrics - Immunization Catch-Up",type:"mc",q:"A 7-year-old migrant child has no immunization records and no documented vaccines. What is the correct approach?",choices:["Assume they were vaccinated and give only boosters","Start the full catch-up schedule per CDC guidelines as if unvaccinated — it is safe to repeat vaccines","Wait for records before giving any vaccines","Give only MMR and skip the rest"],answer:1,explain:"Unknown or uncertain immunization status: administer age-appropriate vaccines per the catch-up schedule as if the child is unimmunized. It is safe to repeat vaccines — there is no increased risk of adverse events from extra doses. Serologic testing is NOT routinely recommended except for varicella and hepatitis B in certain populations."},
  {unit:"U4",topic:"Adolescent - Confidentiality",type:"mc",q:"A 15yo requests STI testing and asks you not to tell their parents. What is the most appropriate response?",choices:["Refuse — minors cannot consent to any care without parents","Provide confidential STI testing and treatment — most states allow minors to consent to STI services without parental notification","Call the parents immediately","Test but tell the parents when results are available"],answer:1,explain:"All 50 states allow minors to consent to STI testing and treatment without parental consent or notification. Some states also allow minors to consent to contraception, mental health services, and substance use treatment. Always verify your state's specific minor consent laws. Discuss confidentiality limits upfront (mandatory reporting for abuse, suicidal ideation, homicide risk)."},
  {unit:"U7",topic:"End of Life - Advance Directives",type:"mc",q:"A patient with terminal cancer wants to discuss end-of-life wishes but their family insists on 'full care.' The patient has capacity. What is the priority?",choices:["Follow the family's wishes","Ask the patient privately what they want — their autonomy is primary as long as they have capacity","Avoid the topic to prevent conflict","Transfer to palliative care without discussion"],answer:1,explain:"A patient with decisional capacity has the right to make their own healthcare decisions, including refusing life-sustaining treatment. Family preferences do NOT override patient autonomy. Facilitate a family meeting to communicate the patient's wishes. Document advance directives, healthcare proxy, and code status. Palliative care consultation can help mediate."},
  {unit:"U7",topic:"Transgender - Hormone Therapy Monitoring",type:"mc",q:"A 25yo transgender woman on estradiol and spironolactone for 6 months asks what labs need monitoring. What is the appropriate monitoring plan?",choices:["No labs needed","Serum estradiol, testosterone, potassium, and prolactin every 3 months for the first year, then every 6-12 months","Only testosterone level annually","Only potassium level"],answer:1,explain:"Transfeminine hormone therapy monitoring: serum estradiol (goal 100-200 pg/mL), testosterone (goal <50 ng/dL), potassium (spironolactone is potassium-sparing), prolactin (estrogen can increase prolactin). Monitor every 3 months in the first year, then every 6-12 months. Also monitor: lipids, LFTs, HbA1c if risk factors. Spironolactone side effects: hyperkalemia, diuresis, orthostasis."},
  {unit:"U7",topic:"Disability - Communication",type:"mc",q:"A patient who is Deaf presents for a clinic visit. They use ASL as their primary language. What is the legally required accommodation under the ADA?",choices:["Ask them to bring a family member to interpret","Provide a qualified ASL medical interpreter at no cost to the patient","Write notes back and forth","Use a translation app on your phone"],answer:1,explain:"ADA requires healthcare providers to provide effective communication for patients with disabilities, including qualified ASL interpreters, at no cost to the patient. Family members should NOT be used as interpreters (privacy, accuracy, conflict of interest). Video remote interpreting (VRI) is acceptable if the technology works reliably. Written notes are insufficient for complex medical discussions."},
  {unit:"U7",topic:"Rural Health - Access",type:"mc",q:"A patient living in a rural area 90 miles from the nearest specialist needs ongoing rheumatology care for lupus. What is the most appropriate care model?",choices:["Tell them to move closer to the city","Telehealth rheumatology consult with local primary care coordination","Discharge from rheumatology care","Wait until they can travel"],answer:1,explain:"Rural patients face significant access barriers: provider shortages, transportation, time off work, cost of travel. Telehealth (when clinically appropriate) with coordination between specialist and local PCP is an evidence-based model. PCP can perform physical exam elements guided by the specialist via telehealth. Other strategies: mobile health units, community health workers, traveling specialist clinics."}
];
